### ISSUE TITLE
Amend text on sign-up page to read 'annual invoice' 

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#277]
On the online sign-up page for Supporters the option to pay by annual invoice should read 'Annual invoice' rather than 'Invoice'.

**Comment by Floppy** [comment]
I think we probably did this in the last round.

**Comment by greenreveller** [comment]
Hiya @Floppy, no it still reads 'invoice' on this page: https://directory.theodi.org/members/new?level=supporter

**Comment by pezholio** [comment]
Yeah, the changes have been merged, but not yet live :smile:
