### ISSUE TITLE
Preview function not working for sponsor badges 

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#295]
In the Member Directory when you go to a sponsor company profile and click 'Display a Badge' you cannot preview the different size/colour badges in the blue sandbox. 

e.g. https://directory.theodi.org/members/QE2834IV

Also when you select 'mini' option it brings up four alignment options for the badge whereas for the other sizes there are only two alignment options 'Right' or 'Left'. Please amend so that the mini option has only 'Right' or 'Left' alignment options. 

NB this is not urgent - we will roll out badges to sponsors after the Summit

**Comment by pkqk** [comment]
This has been fixed with the changes to badges for individuals
