### ISSUE TITLE
Broken sign-in to Member Directory 

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#303]
When I click on 'Administration' on 'https://directory.theodi.org/members' I get sent to the following page with message 'No data received': 

http://directory.theodi.org:443/admins/auth/google_apps/callback?_method=post&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.mode=id_res&openid.op_endpoint=https%3A%2F%2Fwww.google.com%2Fa%2Ftheodi.org%2Fo8%2Fud%3Fbe%3Do8&openid.response_nonce=2014-10-07T10%3A35%3A33ZlPALp-neIYTQaw&openid.return_to=http%3A%2F%2Fdirectory.theodi.org%3A443%2Fadmins%2Fauth%2Fgoogle_apps%2Fcallback%3F_method%3Dpost&openid.assoc_handle=1.AMlYA9WLtSnkkdRUIf50b5fCOvpwmNKTTBdNuLxQ9kHiAIYx3cVN5KE6qcL9WYmL&openid.signed=op_endpoint%2Cclaimed_id%2Cidentity%2Creturn_to%2Cresponse_nonce%2Cassoc_handle%2Cns.ext1%2Cext1.mode%2Cext1.type.ext2%2Cext1.value.ext2%2Cext1.type.ext3%2Cext1.value.ext3%2Cext1.type.ext0%2Cext1.value.ext0&openid.sig=%2BOWSFxVVSxLRIykuRCNWQiZLcTU%3D&openid.identity=http%3A%2F%2Ftheodi.org%2Fopenid%3Fid%3D117640102694529600599&openid.claimed_id=http%3A%2F%2Ftheodi.org%2Fopenid%3Fid%3D117640102694529600599&openid.ns.ext1=http%3A%2F%2Fopenid.net%2Fsrv%2Fax%2F1.0&openid.ext1.mode=fetch_response&openid.ext1.type.ext2=http%3A%2F%2Faxschema.org%2FnamePerson%2Ffirst&openid.ext1.value.ext2=Andrea&openid.ext1.type.ext3=http%3A%2F%2Faxschema.org%2FnamePerson%2Flast&openid.ext1.value.ext3=Cox&openid.ext1.type.ext0=http%3A%2F%2Faxschema.org%2Fcontact%2Femail&openid.ext1.value.ext0=andrea.cox%40theodi.org#

Stuart has found a temporary fix by deleting the 443 from the URL.

**Comment by Floppy** [comment]
Closed and superceded by #360
