### ISSUE TITLE
Add new individual membership tier: 'Individual Supporter'

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#306]
We want to add a new individual membership tier to the Member directory called 'Individual Supporter' at a price of £90 from early January 2015 (exact date tbc).

Internally we will differentiate between Individual Supporters and other Supporters by using the following terms for the following price points: 
Individual Supporter (£90)
SME Supporter (£720)
Corporate Supporter (£2200)

We will need to make the associated changes to reflect the new Individual Supporter tier on the following systems:
Membership pages of website: https://github.com/theodi/member-directory/issues/312 
Online sign-in form: https://github.com/theodi/member-directory/issues/313
Xero, Capsule, Stripe: https://github.com/theodi/member-directory/issues/314
Member Directory: https://github.com/theodi/member-directory/issues/316

Please see linked issues for further information on the requirements for this new tier.

**Comment by Floppy** [comment]
pretty much done, just waiting for merges. See theodi/shared#447
