### ISSUE TITLE
Update signup T&Cs for SME/Corporate Supporters

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#308]
New terms are in https://docs.google.com/a/theodi.org/document/d/1GgUBLiAnVhCOPowqr2cjQDiGYcKzDXAK8kHYN3NGops/edit 

These are currently in draft. They will be finalised by 5 December 2014 by @greenreveller. 

To go live week beginning 5th Jan 2015. @greenreveller to confirm exact date.

**Comment by greenreveller** [comment]
@pezholio  Here are the final versions of the T&Cs: 

Marked up: https://docs.google.com/a/theodi.org/document/d/1GgUBLiAnVhCOPowqr2cjQDiGYcKzDXAK8kHYN3NGops/edit

Clean: https://docs.google.com/a/theodi.org/document/d/1-jClM-GFNtqGVUmH3bFnuoEzfWijYJ4cPZjzJA3X4z4/edit

**Comment by pezholio** [comment]
I've made these changes now. So all should be ready for go live!

**Comment by greenreveller** [comment]
Hi @pezholio, we have a couple more changes to make to the T&Cs. Please see pink text in marked up version for what has been changed. 

https://docs.google.com/a/theodi.org/document/d/1GgUBLiAnVhCOPowqr2cjQDiGYcKzDXAK8kHYN3NGops/edit

This relates to reducing the payment options for SME/Corporate Supporters which I have raised in #309

**Comment by greenreveller** [comment]
Final changes now made to the T&Cs for SMEs/Corporates. 

Please see orange text in marked up version: 
https://docs.google.com/a/theodi.org/document/d/1GgUBLiAnVhCOPowqr2cjQDiGYcKzDXAK8kHYN3NGops/edit

This mirrors the clean version of the T&Cs here: 
https://docs.google.com/a/theodi.org/document/d/1-jClM-GFNtqGVUmH3bFnuoEzfWijYJ4cPZjzJA3X4z4/edit

**Comment by greenreveller** [comment]
Hi @Floppy, there's still 4 changes in pink which haven't made it over to the online form. 

They are all changes which have comments attached to them in the gdoc so perhaps they aren't showing up in pink when you open the document e.g. see pink text and comment about apostrophe in this para

6. 	Membership Renewal 
6.1 Your membership will automatically renew for a period of one year, unless at least 30 days’ prior to the End Date you give written notice to the ODI to terminate your membership

**Comment by Floppy** [comment]
Ah, I don't see any comments at all for some reason.

**Comment by Floppy** [comment]
I've added a missing bit in 5.2, and remove apostrophe in 6.1. What else is there? I don't seem to be able to see any others. Can you put the changes in here?

**Comment by greenreveller** [comment]
that's so weird...

So the other changes are: 
7.1.3. Add link (https://directory.theodi.org/members) to text 'ODI's member directory'
7.1.7. Remove link from text 'Brand Guidelines'
12.2 Missing full stop at the end of the para
