### ISSUE TITLE
Update Corporate Supporter pricing on Stripe, Capsule, Xero, website

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#311]
From 1 Jan 2015 Corporate Supporters will be charged £2,200 + VAT p.a. (rather than £1,440 + VAT p.a.)

Please update the following systems with the new price point so they are ready to go live by early Jan (exact date tbc): 
Stripe
Capsule 
Xero
Website - 
On the following website pages
http://theodi.org/membership - in the blue box at the bottom of the page 
http://theodi.org/odi-supporter - the text above the orange ‘join now’ button

**Comment by Floppy** [comment]
See #314 for stripe changes
