### ISSUE TITLE
Allow Individual Supporters to sign-up for membership online

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#313]
Individual Supporters need to sign up on the ODI website to become a member of the ODI. 

We need to collect the following information from them:

Your Name
(required)
Email Address
(required)

Contact Number

What industry sector do you work in? 

Billing Address
Address
(required)
City
(required)
Region

Country
(required)
Postcode
(required)

Payment method
Credit/Debit Card

Password
Confirm password

I have read and agree to the terms and conditions of membership

Pay Now 

We need to show them the following Terms and Conditions before they sign up: 
https://docs.google.com/a/theodi.org/document/d/1VYVyfPnkhQvSkvxN6aaX1Qprg_YK-uvLEajaYdgsSAw/edit
** NB these Terms and Conditions are different from SME/Corporate Terms and Conditions
** NB these Terms and Conditions are currently in draft form (Georgia to sign off)

----------------------------

Once the Individual Supporter has entered their data and signed up the entry created in Member Directory needs to create entries in Xero, Capsule and Stripe. 

** Individual Supporters cannot pay by annual invoice, only by credit/debit card via Stripe
** Will leave to you to decide whether it's better to create a new Individual Supporter form or whether it is preferable to create a new option within the existing Supporter sign-up form at: https://directory.theodi.org/members/new?level=supporter

**Comment by pezholio** [comment]
@greenreveller Do we have the content for the data protection policy and the right to cancel yet?

**Comment by pezholio** [comment]
Actually, I think the data protection policy has been removed now

**Comment by greenreveller** [comment]
Correct - we decided that we don't need to attach this separately as it's
referenced in the T&Cs


Andrea

Andrea Cox
Membership Manager
@andrea_cox_ <https://twitter.com/andrea_cox_> @UKODImembers
<https://twitter.com/UKODImembers>

The Open Data Institute <http://www.theodi.org/>
Tel +44 (0) 7855 456 002

**Comment by Floppy** [comment]
How about right to cancel? Is that also in the T&Cs?

**Comment by greenreveller** [comment]
Yep - in the T&Cs


Andrea

Andrea Cox
Membership Manager
@andrea_cox_ <https://twitter.com/andrea_cox_> @UKODImembers
<https://twitter.com/UKODImembers>

The Open Data Institute <http://www.theodi.org/>
Tel +44 (0) 7855 456 002

**Comment by Floppy** [comment]
rock and roll

**Comment by greenreveller** [comment]
We've spotted a mistake at the bottom of the form. Please amend: 

You have the right to cancel anytime.

to read

You have the right to cancel within the first 14 days of your membership.

The link to the form should remain.

Thanks

**Comment by greenreveller** [comment]
@Floppy In the html version of the T&Cs which is attached to the welcome email the numbering of the paragraphs has changed from the original version here: https://docs.google.com/a/theodi.org/document/d/1-jClM-GFNtqGVUmH3bFnuoEzfWijYJ4cPZjzJA3X4z4/edit

Is it possible to amend the html so that the paragraph numbering mirrors the gdoc version?

**Comment by Floppy** [comment]
![](http://i563.photobucket.com/albums/ss73/Ynale/EyeRoll.gif)

**Comment by Floppy** [comment]
(joking, of course I will :) )

**Comment by greenreveller** [comment]
Final version of T&Cs signed off from solicitor/Gavin https://docs.google.com/a/theodi.org/document/d/1G7Jzt61f2f7aEBn51qHzJCwfsuhjZAG4fU7t0yoRHT4/edit

New edits/amends in orange 
THANK YOU

**Comment by Floppy** [comment]
![](http://media0.giphy.com/media/3yxADC4jE5W4E/200_s.gif)

**Comment by Floppy** [comment]
@greenreveller I can't access the above document I'm afraid - I did request access, but haven't got it yet.
