### ISSUE TITLE
Add Individual Supporter product to Stripe, Capsule, Xero

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#314]
From Jan 2015 (exact date tbc) Individual Supporter membership will be offered as a product at the price of £90 + VAT p.a. 

Please update the following systems with the new price point so they are ready to go live by early Jan (exact date tbc): 
Stripe
Capsule 
Xero

**Comment by Floppy** [comment]
Required for #335

**Comment by Floppy** [comment]
So.

We need to create new stripe plans:

| ID | period | price (inc VAT) |
|----|------|-----|
| 2015_corporate_supporter_monthly | monthly | 220 |
| 2015_corporate_supporter_annual | annual | 2640 |
| individual_supporter | annual | 108 |

@alisonwalters, can you create these for us in the live stripe system?

**Comment by Floppy** [comment]
Also required for #336

**Comment by alisonwalters** [comment]
Will do.

thanks

Ali

**Comment by greenreveller** [comment]
There is a data linking problem we've uncovered between Stripe and Xero. 

While Supporters are being charged correctly in Stripe the automated invoicing from Stripe to Xero is not calculating the VAT correctly. 

In one instance individual Supporters are being charged £90 + VAT in Stripe but when the invoice is posted in Xero the VAT is being added on again (so the total comes to £129.60). 

In the second instance an SME Supporter has been charged £720 + VAT in Stripe (IT as a Utilities network) but when the invoice is posted in Xero no VAT is showing on the invoice.

**Comment by greenreveller** [comment]
Hi guys, we're still experiencing problems with Xero / Stripe configuration so @alisonwalters and Steph are still having to manually amend invoices. Can someone take a quick look in Stripe/Xero to see what's going on? Thank you!

**Comment by Floppy** [comment]
Can you outline what the actual problem is? What are you seeing vs what you would expect to see?

**Comment by greenreveller** [comment]
See my comment Jan 28 for outline. @alisonwalters can add more detail if you need it.

**Comment by greenreveller** [comment]
Also, @Floppy did you hear back from Capsule/Xero about being able to list someone as a person rather than an organisation? We are still changing this manually in Capsule a few are getting missed so we need to automate the process if/when possible. Thanks,

**Comment by alisonwalters** [comment]
Hi,
I may have missed giving info re listing someone as a person rather than an
organisation. Sorry, pls could you re-iterate?
In Xero, if it is the organisation that is buying, then we need to record
it under the organisation not the person.

Thanks

Ali

**Comment by Floppy** [comment]
@alisonwalters this is a Capsule thing, you don't need to worry. It should be right in Xero. @greenreveller we did hear back, and there's no way to do it via the API. We'll need to write something to drive the website manually, which is a whole new thing and a royal pain in the bum. We'll need to put aside some time for it. Also, sorry for not noticing that the description of the problem was already here - I was just responding via email and didn't see the whole context.

**Comment by greenreveller** [comment]
@Floppy no probs :) and yes, that is a pain! I will make it a separate ticket and then close this ticket. Approx how long do you think the job might take (i'm thinking that if I can secure another week of Adam's time next week he might be able to look at it)

**Comment by Floppy** [comment]
I guess maybe a day, possibly two? It will take a bit of terrible hacking around getting the code to manually log into the website pretending to be a human, which might end up being quite awkward.

**Comment by greenreveller** [comment]
Thanks James. Will add to a new Xero ticket now.
