### ISSUE TITLE
Supporter can't sign in to Member Directory

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#319]
MN8779QJ
Digi2al

Account owner can't sign in. Please could you reset their password? 

Thanks

**Comment by Floppy** [comment]
any update on this one?

**Comment by greenreveller** [comment]
haven't heard back from them - will chase


Andrea

Andrea Cox
Membership Manager
@andrea_cox_ <https://twitter.com/andrea_cox_> @UKODImembers
<https://twitter.com/UKODImembers>

The Open Data Institute <http://www.theodi.org/>
Tel +44 (0) 7855 456 002

**Comment by greenreveller** [comment]
chased again on 16/02/15

**Comment by pkqk** [comment]
I just checked and their account hasn't been confirmed. I'll mark it as confirmed and then the usual password reset flow should work.
