### ISSUE TITLE
Give Clara admin rights to directory.theodi.org

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#339]

**Comment by Floppy** [comment]
All ODI users should be able to log into the admin console already, using their ODI google login details. Does it not work?

**Comment by greenreveller** [comment]
ah - will check....

we're in! Thanks, had forgotten how to log in.

NB Still the same #303 issue (although we have a work around by deleting
the 443 from the URL)


Andrea

Andrea Cox
Membership Manager
@andrea_cox_ <https://twitter.com/andrea_cox_> @UKODImembers
<https://twitter.com/UKODImembers>

The Open Data Institute <http://www.theodi.org/>
Tel +44 (0) 7855 456 002

**Comment by Floppy** [comment]
Great! #303 is in progress...
