### ISSUE TITLE
Supporter can't log in to account

### ISSUE THREAD

**Issue by ClaraLewis** [theodi/member-directory#348]
Informed Solutions, supporter ID EM2331TU can't log in: When trying to access account it asks her to confirm the account before she logs in, but to confirm this she needs to log in.

**Comment by Floppy** [comment]
Hm, interesting. She should have an email in her inbox. Can you check that her email address looks right in the admin interface? If it is, we can resend.

**Comment by greenreveller** [comment]
@ClaraLewis can you update with the latest on this issue here? Thanks

**Comment by ClaraLewis** [comment]
Have changed the account details and supporter has been able to log in successfully.
