### ISSUE TITLE
Supporter entered in Directory but not showing in Capsule

### ISSUE THREAD

**Issue by ClaraLewis** [theodi/member-directory#349]
Esri (Member ID BT0987SX) have completed entry on Directory and are showing up there but not on Capsule.

**Comment by Floppy** [comment]
I think this was a case mismatch (which is unfortunately something we can't fix). I renamed ESRI in capsule to Esri, and the membership registration has now gone through. The other bits will appear over the next 20 minutes.

**Comment by ClaraLewis** [comment]
Thank you kind sir! Btw, what is protocol on replying to fixing issues on
github?

On 19 January 2015 at 12:07, James Smith <notifications@github.com> wrote:

> I think this was a case mismatch (which is unfortunately something we
> can't fix). I renamed ESRI in capsule to Esri, and the membership
> registration has now gone through. The other bits will appear over the next
> 20 minutes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theodi/member-directory/issues/349#issuecomment-70483531>
> .
>



-- 
Clara Lewis, Membership Coordinator theODI.org <http://theodi.org>

+44 020 3598 9395  @ClaraPLewis
The ODI, 65 Clifton Street, London EC2A 4JE <http://www.theodi.org/contact>

**Comment by Floppy** [comment]
It's fine :)
