### ISSUE TITLE
Individual Supporter can't update directory entry details

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#351]
Richard (RW1448ZD) has logged in to member directory and made amends to his directory entry. 

When he tries to save changes they update but he then lands on the following page with this error message:

![image](https://cloud.githubusercontent.com/assets/5023266/5937754/7123a584-a6eb-11e4-92c4-7039d96b492b.png)

**Comment by pkqk** [comment]
Is this happening repeatedly? It looks like it may be that he was signed out due to being inactive for a while.

**Comment by greenreveller** [comment]
ah, no idea. Don't think he's tried again since. I can ask Kat to try the same thing and then update.
