### ISSUE TITLE
Individual Supporters can't download member badge 

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#352]
Individual Supporters get the following page after they click 'Download' in the blue sandbox on their member directory profile: 

https://directory.theodi.org/members/badges/black/170px.png

![image](https://cloud.githubusercontent.com/assets/5023266/5957079/a298cd9e-a7ac-11e4-8cfa-5e4f1cb1ecfb.png)

NB no problems at all when trying to copy code to create a badge
.

**Comment by pkqk** [comment]
ah, the initial download link was wrong. should be fixed now
