### ISSUE TITLE
Function of the 'send me the newsletter' box?

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#353]
What happens if a member ticks the ‘send me the newsletter’ box in their directory entry profile? 

Does it link to the Mailchimp members list? 

If not can we either: 
a. add that feature so that when a member ticks the 'send me the newsletter' box this triggers the member's email address to be added to the ODI members Mailchimp list? 
b. remove the option from all member directory entry profiles

Let me know what you think,, 

Thanks

**Comment by pkqk** [comment]
Looks like we can make it add to the Mailchimp list but it does have to send the mailchimp welcome email which they will need to click the ok link on before they will be added to the list.

If that's ok?

I imagine the tickbox is there as an agreement indicator (legal reasons and all that).

**Comment by greenreveller** [comment]
That's fine by me :) more automation, less manual input - always good. 

Do you need my help in making it sync to Mailchimp?
