### ISSUE TITLE
New member signup for Jisc not showing up

### ISSUE THREAD

**Issue by ClaraLewis** [theodi/member-directory#355]
Have set up new member Jisc on capsule and tagged with membership but they haven't yet been assigned a membership ID and we have not received a welcome email for them. Are they perhaps stuck somewhere? Thanks

**Comment by pezholio** [comment]
For some reason, the member didn't get added to the queue when they got created, so I made a trivial change (added a web address), updated it and kicked the job off manually, and amazingly, it worked! :dancers:
