### ISSUE TITLE
Supporter can't sign in to Member Directory

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#357]
Informed Solutions
EM2331TU

Whenever she tries to log in, it tells her to confirm my account before continuing. 

She doesn't then know how to confirm her account (she can't find the original email with the confirmation URL)

Please help!

**Comment by pkqk** [comment]
@greenreveller There is a link at the bottom of the sign in page that says [Didn't receive confirmation instructions?](https://directory.theodi.org/members/confirmation/new)

She can resend the confirmation email from there, the problem might be that it's registered with another email which is why she may not have received it.

**Comment by greenreveller** [comment]
@pkqk yeah she says she's tried that but it still doesn't let her login after she's clicked on the new link. 

IS there a work around?

**Comment by pkqk** [comment]
@greenreveller can you get her to forward me a copy of the reset email and I'll try and see why it's not working.

**Comment by pkqk** [comment]
It looks like in this case and in #358 that the confirmation link in the welcome email hadn't been clicked.

I'll make it so requesting a password reset and following that link confirms their email as that proves that they are receiving email too and will hopefully help this confusion.

**Comment by greenreveller** [comment]
Brilliant, thanks Adam. Makes sense.


Andrea

Andrea Cox
Membership Manager
@andrea_cox_ <https://twitter.com/andrea_cox_> @UKODImembers
<https://twitter.com/UKODImembers>

The Open Data Institute <http://www.theodi.org/>
Tel +44 (0) 7855 456 002
