### ISSUE TITLE
Supporter not showing up on Directory and can't login

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#359]
Member ID: AI1175KK (NimbleLearn)
They received welcome email but when they try to login again they cannot (even after requesting new confirmation email)
Also, I clicked 'active' on their profile in Capsule 2 hrs ago and their Directory entry has still not gone live.

**Comment by pkqk** [comment]
Has the new email made the confirmation instructions less clear? it's the same problem again, they've not followed the confirmation link.

I can't find any errors about Capsule not setting the entry active, I can change that or it might go through if you toggle it off and then back on.

**Comment by pkqk** [comment]
I've marked them as active now, they should be able to log in, or request a password reset if they need to.
