### ISSUE TITLE
Supporter missing from Xero (MK0502DF)

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#370]
Supporter (University College London) showing in Capsule but invoice has not been drafted in Xero.

**Comment by pezholio** [comment]
Can you check if it's shown up yet? Can't see anything obvious that's gone wrong

**Comment by greenreveller** [comment]
Nope, still can't see anything in Xero :(

For context I added them manually in Capsule, they received the auto welcome email ok but just not syncing with Xero.

**Comment by pezholio** [comment]
Hmmmm... That's odd. Are they showing in the member directory?

**Comment by greenreveller** [comment]
nope

**Comment by pezholio** [comment]
Cool, I've just kicked the invoicer off manually. Can you have another peek?

**Comment by greenreveller** [comment]
Yep now in Xero but invoice is for corporate supporter rather than supporter (they're listed as supporter in Capsule). Also it says that they have paid with credit card (which they obv haven't yet!)

![image](https://cloud.githubusercontent.com/assets/5023266/6637054/ac3a00b0-c96d-11e4-8887-68b7790aacc3.png)

Can you change at your end?

**Comment by pezholio** [comment]
Everything seems right at my end, oddly. Can you change in Xero? Lemme know if this happens again

**Comment by greenreveller** [comment]
don't know if I can change in Xero :/

why did it come through corporate supporter rather than supporter? weird

**Comment by pezholio** [comment]
Erm, I'm not sure TBH. I'll have to chase it through. Can you delete the invoice and maybe I can try again?

**Comment by greenreveller** [comment]
deleted

**Comment by pezholio** [comment]
Oh, hang on. Looking at #368, we're using Chargify for invoicing now? I'm not sure how this'll work for members that are added manually. @pkqk is probably the man to speak to about this.

**Comment by greenreveller** [comment]
ah, I didn't realise that it would apply just to those we added manually via Capsule. No matter. This is a one off so we can draft up an manual invoice in Xero (just wanted to check that there was no draft invoice stuck in the queue). 

Thanks for investigating @pezholio

**Comment by pezholio** [comment]
No probs :smile_cat:
