### ISSUE TITLE
Automate membership count in a google doc

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#371]
As membership manager I want to see how many members of each tier we have in the programme at any one time in this document: https://docs.google.com/a/theodi.org/spreadsheet/ccc?key=0Aol2NcZf-p7GdEZKSUxTNDV6R2FKenNMdkI0dUZ4WGc&usp=drive_web#gid=0

Currently the data in the google document is a manually updated from a number of sources but this is proving very time consuming as we grow. 

The data exists in Capsule (captured by datatags against people or organisations: supporter [supporter or corporate supporter]; member;sponsor;partner;individual). 

It is not possible to create a custom report which lists the number of all of these membership categories. Capsule Support have also confirmed that we would need to build our own tool for the API so we can update the Gdoc with an automatic count .

@Floppy has estimated that this will take c.1 day of development time.

**Comment by alisonwalters** [comment]
Thanks for the update :)

**Comment by pkqk** [comment]
I've made it so you can access the counts from google docs based on the member directory.

The data might need a little cleaning up but an example spreadsheet is here:
https://docs.google.com/spreadsheets/d/1EAVgtObxXmhqkVNbYDnOpVWUDfMXr2W0WeBfO-RJNaM/edit#gid=0
