### ISSUE TITLE
Individual Supporter not showing up in Capsule

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#372]
Supporter OJ1760GH is showing up in Xero but not in Capsule (hence is not being counted in our membership total).  He already has an entry in Capsule (as a person but with his work email) which might be the issue?

**Comment by greenreveller** [comment]
Still can't see Mark Braggins showing up in Capsule - can you have a look into this please? @pezholio @pkqk ?

**Comment by pkqk** [comment]
I've set it to try saving to capsule again. I'll look into it again if that doesn't succeed.

**Comment by greenreveller** [comment]
Added manually to Capsule
