### ISSUE TITLE
OpenDataSoft (Member number DZ8030ZI) not showing up in Capsule

### ISSUE THREAD

**Issue by BertLewis** [theodi/member-directory#378]
Hiya :) OpenDataSoft are now members and have had their welcome email but not showing up in capsule - whyyyyy? :) Thank you (it was Friday when I wrote this message.)

**Comment by pezholio** [comment]
Looking at this, it seems that they're listed as OpendataSoft in Capsule, and added as OpenDataSoft in the member directory. Need to fix the underlying issue, but, for now, I've altered the listing in Capsule to match the correct capitalisation. Should start trickling through shortly :smile:

**Comment by Floppy** [comment]
ah, the good old case problem. Another annoying aspect of the API we can't work around.

**Comment by pezholio** [comment]
Ah, the API query is case insensitive, it's just the filter afterwards that chokes. We can use a regex or something to get round that.

**Comment by Floppy** [comment]
Oh, really? I thought I looked at that and couldn't do it. I am pretty thick though and my mind is fuddled by spreadsheets these days.

**Comment by pezholio** [comment]
All seems to be good in Capsule now - @ClaraLewis can you have a look and close if you're happy?

**Comment by BertLewis** [comment]
Thank you @pezholio!
