### ISSUE TITLE
Two new individual Supporters not showing up in Capsule

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#379]
Hey, member EO2004QF (Greg Elliott) is not showing up as organisations in Capsule (in order for us to convert him to 'person' and then get the membership tag assigned).

May be because we already has his email on the system. 

Also QO3986AI (Andreas Heinimann) not showing up at all in Capsule.

Can you check the queue? Cheers,

**Comment by ClaraLewis** [comment]
Hi all, I think probably the same issue - new individual supporter Donna Lindsay (UU8915ME) is also not showing up on Capsule at all.

**Comment by pezholio** [comment]
Fix for this coming down the pipes. Will probably have to kick them back off manually, so please let me know if there's any more missing

**Comment by BertLewis** [comment]
Thanks Stu, I'll let you know if others aren't showing up.

On 16 April 2015 at 10:45, pezholio <notifications@github.com> wrote:

> Fix for this coming down the pipes. Will probably have to kick them back
> off manually, so please let me know if there's any more missing
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theodi/member-directory/issues/379#issuecomment-93694383>
> .
>



-- 
Clara Lewis, Membership| Evidence| Project Support theODI.org
<http://theodi.org>

+44 020 3598 9395  @ClaraPLewis @ODIHQmembers
The ODI, 65 Clifton Street, London EC2A 4JE <http://www.theodi.org/contact>

**Comment by pezholio** [comment]
I've kicked those off and they should be coming down the pipe shortly :+1:

**Comment by BertLewis** [comment]
Thanks Stu. I'm not sure if it's related or even a problem yet but Peter
Hicks has just signed up as an Ind Supporter (*BX3561TS*) and he's showing
up in capsule but membership tag not showing - may just have to wait a
while.

On 16 April 2015 at 12:52, pezholio <notifications@github.com> wrote:

> I've kicked those off and they should be coming down the pipe shortly [image:
> :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theodi/member-directory/issues/379#issuecomment-93716129>
> .
>



-- 
Clara Lewis, Membership| Evidence| Project Support theODI.org
<http://theodi.org>

+44 020 3598 9395  @ClaraPLewis @ODIHQmembers
The ODI, 65 Clifton Street, London EC2A 4JE <http://www.theodi.org/contact>

**Comment by pezholio** [comment]
Ah, it might be. I think he's in Capsule already from previous interactions. Have manually kicked him off too

**Comment by greenreveller** [comment]
Hey @BertLewis the membership tag will only show up once we have converted him to a person. Weird thing with Capsule system :/ looks like he's tagged correctly now

**Comment by BertLewis** [comment]
Yep, that's the problem.

On 16 April 2015 at 12:56, Andrea <notifications@github.com> wrote:

> Hey @BertLewis <https://github.com/BertLewis> the membership tag will
> only show up once we have converted him to a person. Weird thing with
> Capsule system :/ looks like he's tagged correctly now
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theodi/member-directory/issues/379#issuecomment-93716745>
> .
>



-- 
Clara Lewis, Membership| Evidence| Project Support theODI.org
<http://theodi.org>

+44 020 3598 9395  @ClaraPLewis @ODIHQmembers
The ODI, 65 Clifton Street, London EC2A 4JE <http://www.theodi.org/contact>

**Comment by BertLewis** [comment]
And thanks Stu, I'll have a look again a bit later to see if they're all
showing up.

On 16 April 2015 at 12:59, Clara Lewis <clara.lewis@theodi.org> wrote:

> Yep, that's the problem.
>
> On 16 April 2015 at 12:56, Andrea <notifications@github.com> wrote:
>
>> Hey @BertLewis <https://github.com/BertLewis> the membership tag will
>> only show up once we have converted him to a person. Weird thing with
>> Capsule system :/ looks like he's tagged correctly now
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/theodi/member-directory/issues/379#issuecomment-93716745>
>> .
>>
>
>
>
> --
> Clara Lewis, Membership| Evidence| Project Support theODI.org
> <http://theodi.org>
>
> +44 020 3598 9395  @ClaraPLewis @ODIHQmembers
> The ODI, 65 Clifton Street, London EC2A 4JE
> <http://www.theodi.org/contact>
>
>


-- 
Clara Lewis, Membership| Evidence| Project Support theODI.org
<http://theodi.org>

+44 020 3598 9395  @ClaraPLewis @ODIHQmembers
The ODI, 65 Clifton Street, London EC2A 4JE <http://www.theodi.org/contact>

**Comment by greenreveller** [comment]
ready to close? @BertLewis
