### ISSUE TITLE
Finance Report coupon and discount data

### ISSUE THREAD

**Issue by pkqk** [theodi/member-directory#380]
![reports](https://cloud.githubusercontent.com/assets/5235/7139246/1a7527d6-e2bd-11e4-9105-3afb6ec5d91a.jpeg)

  1. Add coupon-code used and referral code columns to cash report
  2. Booking value report needs to have products paid at full price, and then each discount applied in separate rows. Roll up total would be useful
  3. Referral summary should be how many of each product (only individual) with referral code, count, net, tax, total
 4. Referral summary should pick up if a sale is immediately refunded and not include it in the report.

**Comment by jordelver** [comment]
It would be useful to see an example of a report with the required changes added so that I can see exactly what we're looking for. Is that possible?

**Comment by greenreveller** [comment]
Agree - @alisonwalters is this something you can draft up by the end of the week? 

Cheers,
