### ISSUE TITLE
New individual supporter not showing up in Capsule

### ISSUE THREAD

**Issue by BertLewis** [theodi/member-directory#382]
New individual supporter Donna Lindsay (UU8915ME) is also not showing up on Capsule at all.

**Comment by BertLewis** [comment]
Individual Supporter Alexander May (ER6131PG) is also not showing up in Capsule at all.

**Comment by greenreveller** [comment]
@BertLewis  is this issue ready to close?

**Comment by BertLewis** [comment]
I think so - I thought there might be some other underlying issue so wasn't sure - I'll close now anyway.
