### ISSUE TITLE
After adding Supporter manually via Capsule they cannot login using member ID

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#384]
Sunderland council (TV5229EO) couldn't pay by credit card for membership so we manually invoiced them as a one off. We added them on Capsule with membership tag and sent an invoice. 

However, now when they try to log in they are a) unable to login using the password they set up at registration b) once the password has been changed they are sent to the pay now page. I am forwarding his email explaining the situation now. 

Can we override the pay now page in this instance?

**Comment by pkqk** [comment]
I've marked them as paid up and active in the database so they should be able to log in properly now.

Are others going to be added by invoice or is this the only one, as it's going to trigger this issue each time?

**Comment by greenreveller** [comment]
thanks @pkqk, will let them know. we're aiming not to do this at all but there is one more coming down the pipeline where it's going to be unavoidable. Will flag up to you as soon as i know when.
