### ISSUE TITLE
Creation of members from Capsule fails

### ISSUE THREAD

**Issue by pkqk** [theodi/member-directory#386]
It leaves the member in an inconsistent state that prevents the user from logging in.

If not enough information is provided it fails to create the organization which will prevent the account page from loading.

**Comment by jordelver** [comment]
What is the desired outcome from this @greenreveller? I'm assuming we cannot validate that enough information is entered into Capsule CRM?

**Comment by greenreveller** [comment]
I don't know what information is required from Capsule for the member account to be created. If we know what MUST be filled in then we can add it to the membership notes - might be a workaround?

**Comment by jordelver** [comment]
Ah, ok. Does that sound like a workaround @pkqk? ^^^

**Comment by pkqk** [comment]
I've not looked into capsule enough, it might be possible to set the fields to be required on that end too which would be handy.

But otherwise yeah document which fields are required and put it in a doc somewhere for when membership are adding someone manually @jordelver

**Comment by jordelver** [comment]
Oh, right, cool. I'll look into whether we can set the fields that are required on Capsule. Where do we usually document such things? @pkqk @greenreveller

**Comment by jordelver** [comment]
I now have access to the document

**Comment by jordelver** [comment]
After much experimentation, I think I've figured out what is required to create members via Capsule.

The required fields are:

* For Organizations
  * Name
  * Email
  * Membership tag - Product Name
  * Membership tag - Email
* For People
  * First name
  * Last name
  * Email
  * Membership tag - Product Name
  * Membership tag - Email

I've documented this in the Google doc.

I was able to login as these members and the account page loaded fine.

You get an email when the member creation fails but before it was only covering the missing email address. I've now changed this email to include more information about what to do in the event of failure.

**Comment by greenreveller** [comment]
Great, thanks @jordelver that's much clearer for us. Ready to test as soon as merged.

**Comment by greenreveller** [comment]
Individual Supporters tested 
Correct information in Capsule - test passed (welcome email, login successful)
Missing information in Capsule - test passed (missing info email to members@theodi.org)

**Comment by greenreveller** [comment]
Individual Supporter tested with a different email in capsule entry to membership tag entry: 

![image](https://cloud.githubusercontent.com/assets/5023266/9603832/68703e6a-50ab-11e5-947f-e8ccc2a82ddf.png)

Capsule: andrea.cox+individualmanual3@theodi.org
Membership tag: andrea.cox+individualmanual4@theodi.org
Initially I received a member welcome email at 12.05 to andrea.cox+individualmanual4@theodi.org
Then I received a missing information email to members@theodi.org re http://theodi.capsulecrm.com/party/88006669 at 13.05

**Comment by greenreveller** [comment]
Individual Supporters tested with correct information in Capsule - test passed (andrea.cox+individualmanual5@theodi.org)
- Welcome email received
- Login successful

**Comment by greenreveller** [comment]
SME Supporter & Corporate Supporters & student supportesr tested with correct information in Capsule - tests passed
Welcome email received
Login successful

**Comment by greenreveller** [comment]
Student tested with correct information (andrea.cox+studentmanual@theodi.org) and received welcome email at 15.05 but also missing information email at 16.05

**Comment by greenreveller** [comment]
Correct data entered for andrea.cox+studentmanual4@theodi.org, welcome email generated as well as capsule error email: https://theodi.capsulecrm.com/party/88094350

**Comment by jordelver** [comment]
Is this one done @greenreveller?
