### ISSUE TITLE
Chargify::Coupon.all does not return all coupons

### ISSUE THREAD

**Issue by pkqk** [theodi/member-directory#387]
Contrary to the docs it also does not return all for the first product family but instead one from each.

Fetch all from each product family in order to fix

**Comment by greenreveller** [comment]
@jordelver I'm about to create a new coupon in Chargify for supporters - does this ticket need to be addressed before the coupon will be recognised correctly?

**Comment by jordelver** [comment]
No, this doesn't need to be done, but we will need to restart the website. Let me know once you've done it and I'll ask someone to do it.

**Comment by greenreveller** [comment]
Thanks Jordan, have created coupon now.

Andrea

Andrea Cox
Membership Manager
@greenreveller <https://twitter.com/greenreveller> @ODIHQmembers
<https://twitter.com/ODIHQmembers>
The Open Data Institute <http://www.theodi.org/>
Tel +44 (0) 7855 456 002

*Summit **2015* <http://summit.theodi.org/> The world's leading event for
showcasing innovation & excellence in open data globally, returns to BFI
Southbank 3 November.

**Comment by jordelver** [comment]
Ok, I'm about to merge in the latest changes and the site will be restarted as part of that process.

**Comment by greenreveller** [comment]
:+1:

**Comment by Floppy** [comment]
code all gone now
