### ISSUE TITLE
New individual supporters not showing up in Capsule

### ISSUE THREAD

**Issue by BertLewis** [theodi/member-directory#389]
A whole troop of them not showing up including David Branch (LH9023FJ), Ken Enright (DV6555QY), Zuz Kopecka (MD6749VA), Joseph Chittenden-Veal (RE2054JO), Kealy Cozens (MS5393FO).

**Comment by BertLewis** [comment]
@pkqk @pezholio can you pick this up please? (Soz, don't seem to have permission to assign people it seems)

**Comment by pkqk** [comment]
I've triggered the jobs that should add them to Capsule.

**Comment by BertLewis** [comment]
Tim Rodgers (EI0908RH) is not showing up at all

**Comment by greenreveller** [comment]
Clara, is this one still outstanding?


Andrea

Andrea Cox
Membership Manager
@andrea_cox_ <https://twitter.com/andrea_cox_> @ODIHQmembers
<https://twitter.com/ODIHQmembers>

The Open Data Institute <http://www.theodi.org/>
Tel +44 (0) 7855 456 002

**Comment by pezholio** [comment]
He's in Capsule, but still an organisation. Have converted him and kicked the job off :+1:

**Comment by pezholio** [comment]
Sorted :smile:
