### ISSUE TITLE
ONS trying to register as corporate Supporter but not able to

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#390]
ONS previously tried to sign up as an individual supporter (QG9949OG) however they did not pay as they realised this was a mistake. 

They would now like to sign up as a corporate supporter but when they login using the above member ID they are not obviously not able to change the product.

I have asked them to register as a Supporter with a new email address (one which has 'digital' in it). When they try this it says that the email is already registered. 

Gah! Help pretty please?!?

**Comment by pkqk** [comment]
@greenreveller do you know what email they're using. There are no ONS emails in the system apart from Terry Makewell (QG9949OG) who has signed ONS up as a large non commercial organisation. Though that's not been paid yet.

**Comment by greenreveller** [comment]
Have asked her for specific address. 

I've already asked her to sign in with that member ID and the original email address terry.makewell@ons.gsi.gov.uk but she seems to be saying that she couldn't change payment so that they are registered as a corporate Supporter. 

From your pov if they login using QG9949OG what page should they land on? Will they be registered as corporate supporter?

**Comment by pkqk** [comment]
Just tested it on my machine (base on a backup of the database) it should take them to the payment summary page and tell them that it's £720 a year.

**Comment by BertLewis** [comment]
Heya, they should be registered as a corporate supporter (at 2200) not at 720 - how do we change that?

**Comment by greenreveller** [comment]
@pkqk Office for National Statistics is registered correctly on Capsule as Corporate Supporter (but without member ID). 

Their member ID was assigned in the system as QG9949OG when they first got half way through sign up as an individual supporter (they started a sign-up as an individual by mistake with email: terry.makewell@ons.gsi.gov.uk)

When you go to https://directory.theodi.org/members/QG9949OG it takes you to the payment page but asks you for £90 payment as an individual Supporter. 

We need them to sign up at corporate Supporter £2,200 + VAT rate. 

They've tried to register Office for National Statistics under a different email: terry.makewell@digital.ons.gov.uk. However, the Office for National Statistics company name is already registered so when they try to sign up they are told that the organisation name is already taken. 

How can we proceed?  Couple of potential options that I can see....
a) raise an invoice manually (but they still won't be able to sign in/have the correct ID assigned to them?)
b) delete company / person from Capsule and Directory back-end and start again?

(NB end of month is today so it would be fantastic if we could sign them up by close of play). 




Welcome email has not been sent to terry.makewell@ons.gsi.gov.uk

**Comment by alisonwalters** [comment]
Hi,
I would suggest option b in the first instance if that is possible.

Ali

**Comment by greenreveller** [comment]
will it be sufficient to delete all data from capsule or do you need to do it from backend?

**Comment by alisonwalters** [comment]
Not sure...I think it safer if Adam answers this question. My guess is that
their info will need to be deleted from chargify as this is the basis of
the sign up process on which everything else relies.

Ali

**Comment by pkqk** [comment]
I've checked that the correct options are set to get the 2200 + VAT price.

A password reset email has been sent so they can log in and proceed to payment. If that works then everything should work out fine.

Viewing their payment page when logged in as an admin probably won't show the correct info as the system isn't designed to do that properly.
