### ISSUE TITLE
Need to add Supporter (Glasgow) manually to systems

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#391]
Glasgow City Council can't pay by credit/debit card so we need to add them to pay by invoice. 

Haven't done anything yet but have all their details ready. @pkqk let me know when I'm good to add them to Capsule and tag them as members. 

Cheers

**Comment by pkqk** [comment]
@greenreveller Add them and see what happens, the problem with the other one was caused by the organisation already existing as they'd already tried to sign up.

**Comment by greenreveller** [comment]
have added *waits with baited breath*

**Comment by greenreveller** [comment]
Just checked and Glasgow are tagged with membership now but have not received a welcome email and no invoice has been drafted for them :/ manual intervention?

**Comment by pkqk** [comment]
@greenreveller :( probably, can you remind me in the morning and I'll have a look.

**Comment by pkqk** [comment]
The 3 different accounts have been consolidated onto one email address and linked with the correct organisation.

Welcome email should've been sent out and 🙏 hopefully the invoice should've been created.

**Comment by greenreveller** [comment]
Glasgow are registered as members in Capsule and have been sent a manual invoice. They can login to the member directory but are being directed to the payment page rather than to their account page. @pkqk Can we set their account to bypass the payment page as with #384?

**Comment by pkqk** [comment]
I've marked them as current so they should be able to log in normally now.

**Comment by greenreveller** [comment]
I have changed the account email for Glasgow. Normally this would trigger a new welcome email to the new account holder but nothing has come through (after 2 hours). Could you check the queue and kickstart if necessary? 
Cheers

**Comment by Floppy** [comment]
um; the contact email looks like complete gibberish in the directory app. I'll check what it should be in capsuleCRM and update.

**Comment by Floppy** [comment]
Hm, the change isn't syncing back for some reason. That's annoying.

**Comment by Floppy** [comment]
There are multiple records associated with the same organization. This is wrong, and probably causing issues. I'll have a clearup.

**Comment by greenreveller** [comment]
Thanks James - can you ping me when it's done so I can get back to Gerry? Cheers

**Comment by Floppy** [comment]
Done.
