### ISSUE TITLE
rogue invoices

### ISSUE THREAD

**Issue by alisonwalters** [theodi/member-directory#392]
Invoices are appearing in Xero drafts that are incorrect in a number of ways:
1 they are recurring month on month when they shouldn't eg Mark BAraggins purchased individual membership in March but we have received another invoice in April, but not another payment for an individual membership in April
2 They are coming through with the wrong amounts eg SME's with a corporate price tag
3 They are coming through when no payment has been made in Stripe eg OPen Corprorates on 13th March
4 13th MArch seemed to generate a lot of rogue invoices

thanks for looking into

A

**Comment by greenreveller** [comment]
Hi @alisonwalters, rogue invoices were generated by using transferring all our contacts into Chargify. We decided that we would wait for a while before turning off the Chargify/Xero link so that you could cross-check numbers for end of month reporting. On that point you just need to let us know when you're happy to turn off the link between Chargify and Xero and then you'll no longer get new draft invoices and you can delete the draft ones as well.

**Comment by alisonwalters** [comment]
Andrea,
thanks for clearing up the confusion. We had thought that but then the
theory moved on...and on......we're now at aliens :)
 We've had confirmation from PWC that we are in order (minor tweak needed
but Adam sorted in two seconds).

We will wait for the April month end report and check everything is OK and
then we can switch off the link.

Brilliant, thanks all

Ali

**Comment by greenreveller** [comment]
Hiya @alisonwalters. Great to hear about PwC - phew!

Just on your specific points: 
1 they are recurring month on month when they shouldn't eg Mark BAraggins purchased individual membership in March but we have received another invoice in April, but not another payment for an individual membership in April - as long as you don't send the invoices this is, I think, not a problem? Or can you just delete?
2 They are coming through with the wrong amounts eg SME's with a corporate price tag - yep, something weird about the linking with Chargify and Xero (will stop happening once you give us the go ahead)
3 They are coming through when no payment has been made in Stripe eg OPen Corprorates on 13th March - they are on £0 for the first year as they are ex-supporter
4 13th MArch seemed to generate a lot of rogue invoices - that was the day we transferred customer data into Stripe

**Comment by alisonwalters** [comment]
thanks Andrea......agreed on all accounts :)
There were also the added rogue invoices due to coupons, but this too will
be sorted once we turn off invoicing.
The solution is actually quite simple for the many errors and we should be
in shape to implement the turn off after month end :)

Best

Ali

**Comment by greenreveller** [comment]
Yay!!! :)
