### ISSUE TITLE
New individual supporters not tagging with membership up in Capsule

### ISSUE THREAD

**Issue by BertLewis** [theodi/member-directory#393]
Hiya,

Matthew Brown XA2135UV, Cimeon Ellerton TK5408IC, Sepi Chakaveh BU8496CX, Evgeny Styrin WL5551AV are not tagging with membership in capsule. I don't know if this is something that can be fixed from our end but it would be super if we could fix it. I can try tagging manually for the time being.

**Comment by greenreveller** [comment]
hi @BertLewis, don't tag manually until you get word from @pkqk that it's ok to do

**Comment by BertLewis** [comment]
Crap, just did that.

**Comment by BertLewis** [comment]
@pkqk I'm going to back away slowly. Let me know what I should do/ when I should do something.

**Comment by pkqk** [comment]
@BertLewis it won't have broken anything. The only thing they might be missing is information such as join date, email, supporter level on the tag. I'm not sure how important that info is to have in Capsule?

@pezholio or @floppy might know more about what it's supposed to be doing.

![this is fine](http://i.imgur.com/u02K30c.png)
