### ISSUE TITLE
Find out why Capsule entries return 'Mailchimp:invalid'

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#394]
@greenreveller and @bertlewis to investigate

**Comment by greenreveller** [comment]
@bertlewis - when you have a mo can you update this ticket on what you found were causes of the Mailchimp:invalid and then close it? Cheers m'dear

**Comment by BertLewis** [comment]
It seems entries return Mailchimp:invalid when the Contacts section has no email address entered - ie it's not just the membership contact details that need to filled in but all fields where an email address could be entered. The other factor is when emails are for a mailing group such as info@, support@, help@ etc so we need a unique person email address.
