### ISSUE TITLE
Booking value overcount ASAP

### ISSUE THREAD

**Issue by pkqk** [theodi/member-directory#396]
If a membership is cancelled in the same month the count doesn't reflect the drop in memberships.

Need to account for drop in number in booking value report.

  - [ ] add number of refunds to booking value report so it's clear that the number has dropped.

**Comment by jordelver** [comment]
> add number of refunds to booking value report so it's clear that the number has dropped.

What should this look like? Again, an example would be ideal.

**Comment by greenreveller** [comment]
@alisonwalters

**Comment by greenreveller** [comment]
This is with finance and membership teams to discuss requirements - on hold for now
