### ISSUE TITLE
Booking value report needs to break down by pricing ASAP

### ISSUE THREAD

**Issue by pkqk** [theodi/member-directory#398]
Membership at a price needs to be counted separately to Membership at a discount.

**Comment by jordelver** [comment]
Not sure what needs to happen for this? Can you give an example?

**Comment by greenreveller** [comment]
@alisonwalters

**Comment by greenreveller** [comment]
Membership products need to be broken down by (live) coupons as per: 
https://docs.google.com/spreadsheets/d/14SgdTL97Y0kweNEFhykxjGXPkCaJ-gxcPzL3AAE-mmc/edit#gid=1149035104
