### ISSUE TITLE
c.10 Individual Supporters not tagging with membership (after converting to person)

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#400]
I converted a whole bunch of Capsule entries from organisation to person during the day but they are still not showing up as tagged with membership (normally doesn't take this long). @pezholio can see you see any obvious issues in the backend?

**Comment by pezholio** [comment]
Can you get into Capsule at all? I just tried and I get an error page

**Comment by greenreveller** [comment]
Yep it's opening fine for me

**Comment by pezholio** [comment]
Hrm. I can't seem to log in.

**Comment by pezholio** [comment]
I'm in now. A lot of people have emails missing. Suspect something has gone screwy with the Capsule / Xero integration. I'll leave it over the weekend and see if it rights itself. If it's still not working on Monday, I'll speak to Capsule and see what's going on

**Comment by greenreveller** [comment]
cool, thanks Stu

**Comment by greenreveller** [comment]
morning Stu, did it sort itself over the weekend?

**Comment by pezholio** [comment]
It did not :angry: 

Just looking and it seems the emails aren't getting passed to Xero for some reason, which means they aren't getting carried into Capsule. Investigating a bit more.

**Comment by pezholio** [comment]
Yup, that's definitely what's happened. I don't know why, because Xero haven't changed their API (that I can see), but emails are definitely missing from the contacts in Xero. A quick fix to this would be to add the emails manually, but I know that's a hassle.

**Comment by greenreveller** [comment]
This is still an issue. See point 3 in this doc: https://docs.google.com/document/d/1hSK2vY7S5aQ6LE8LpO7-_gA4GclAEbao0GWU8TuHaKM/edit
