### ISSUE TITLE
Individual Supporters don't have a first name field filled in in Capsule

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#402]
The member directory is combining first name + last name fields when Individual Supporters sign-up. This means that in Capsule (and in Mailchimp which is linked to Capsule) has no first name data. Hence when we send out mailings to the group there is a blank where there should be a first name. Please help!
cc @bertlewis

**Comment by greenreveller** [comment]
@pkqk could you give a quick summary of what needs to be done to sort this? (even if not you who will do fixing)? Ta,

**Comment by pkqk** [comment]
Probably @pezholio that will be looking at it.

It will be something to do with the names being stored as a single field in the directory database but as first/last name in Capsule/Xero/Chargify.

The name that gets sent to Chargify gets split into first and last name based on guessing but no where else so it's probably going to be somewhere in the integrations that needs fixing.
