### ISSUE TITLE
Individual Supporter Laura Coombes (UA6870SG) not tagging in capsule

### ISSUE THREAD

**Issue by BertLewis** [theodi/member-directory#409]
This is probably because we already had her in Capsule as the main contact for BPE Solicitors (who are no longer members anyway).

**Comment by pezholio** [comment]
Yeah, if you add her manually, everything should work as expected. Fix is incoming for this, but everyone's in meetings at the mo.

**Comment by BertLewis** [comment]
Ah cool, thanks very much @pezholio, will do so.
