### ISSUE TITLE
Have added new member manually in Capsule but no welcome email triggered.

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#410]
The company is Transport Systems Catapult and the contact is Lauren Macdonald (lauren.mcdonald@ts.catapult.org.uk). They did try and sign up once before (XH8832CZ) but never completed their membership. It may be that the member directory is confused by the fact that the email has been used once before for a sign up? 

Cheers,

**Comment by greenreveller** [comment]
@pezholio if you have a spare ten mins today could you see if you can find anything on these guys in the queue? Am trying to get them into May figures for sales

**Comment by pezholio** [comment]
That's really odd. There's actually nothing at all in the queue. I'll have a look and see if I can apply their membership number manually.

**Comment by pezholio** [comment]
Just looked and we don't have anyone with that email in the database. The only organisation with that name has the membership with the old membership number associated

**Comment by greenreveller** [comment]
is it possible to resend the old welcome email to them?

**Comment by pezholio** [comment]
Yeah, I think so. They can also log in with their email address now don't forget :)

**Comment by greenreveller** [comment]
yes, but they were getting really confused by that so we thought better just to trigger a new one. Is that ok?

**Comment by pezholio** [comment]
Yeah, no probs

**Comment by greenreveller** [comment]
ta v.much

**Comment by pezholio** [comment]
Done :+1:

**Comment by greenreveller** [comment]
can't see them showing up in capsule (XH8832CZ) - i reckon it's been a couple of hours. can you see if they're stuck in queue?
