### ISSUE TITLE
Individual Supporter Hamida Ali (HK0151QO) not showing up in capsule

### ISSUE THREAD

**Issue by BertLewis** [theodi/member-directory#411]
She came through yesterday afternoon and hasn't appeared yet in capsule.

**Comment by greenreveller** [comment]
is this one we just need to do manually?

**Comment by BertLewis** [comment]
I wondered if maybe she's just stuck and needs a kick from @pezholio?

**Comment by greenreveller** [comment]
I think in this instance just add her manually so our numbers match
