### ISSUE TITLE
Member (XH8832CZ) paying via invoice. Need to reroute them past payment page

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#412]
We added Transport Systems Catapult manually as a member on Friday as they need to pay by invoice. 

When they click on the link in the welcome email it's taking them through to the Chargify payment page as the Directory has marked them as not having paid yet.

Please can we override this in this instance and send them a link which will take them straight to the member directory profile page? Cheers.

@pezholio - Adam has done this before so can show you how to do this if it's not clear (@pkqk)

**Comment by greenreveller** [comment]
@pezholio hiya Stu, if you have time today could you have a look at this issu? am being chased by member as they can't login. Cheers

**Comment by pezholio** [comment]
That's now done. They should be able to log in now

**Comment by greenreveller** [comment]
Thanks very much Stu, I'll let them know

Andrea

Andrea Cox
Membership Manager
@greenreveller <https://twitter.com/greenreveller> @ODIHQmembers
<https://twitter.com/ODIHQmembers>

The Open Data Institute <http://www.theodi.org/>
Tel +44 (0) 7855 456 002
