### ISSUE TITLE
Need to reintroduce the option to pay by invoice for members

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#413]
Increasingly we have members who need to pay for membership by invoice. We had turned off this option when we integrated Chargify in the hope that we could get everyone to pay by credit/debit card. Sadly, this hasn't happened! 

If a member now needs to pay by invoice the system currently is as follows:
- Membership team registers the member manually on Capsule (by adding membership tag)
- Welcome email triggered 

However, when members who are paying by invoice click on the link in the welcome email they are being sent to the Chargify payment page (see #412).

In future we need the link in the welcome email to automatically send members who are paying by invoice to their member directory profile page (i.e. bypass the Chargify payment page). 

cc @pezholio @pkqk @alisonwalters

**Comment by greenreveller** [comment]
This will be need to be ready to go for the start of Summit ticket sales so that we can bypass the membership payment pages where Summit ticket prices include membership. @langphil - when is scheduled launch date for sales?

**Comment by langphil** [comment]
Hi, 

We’re aiming to launch trust and enterprise tickets this afternoon (4/6). It’ll be a soft launch with no promotion. 

-- 
Phil Lang - Digital Production Editor
@ODIHQ | thodi.org
@langphil | 0741 44 63047

On 4 June 2015 at 13:35:00, Andrea (notifications@github.com) wrote:

This will be need to be ready to go for the start of Summit ticket sales so that we can bypass the membership payment pages where Summit ticket prices include membership. @langphil - when is scheduled launch date for sales?

**Comment by greenreveller** [comment]
and the full launch?

**Comment by langphil** [comment]
You can take it as being the full launch today, we just won’t begin marketing it yet. We just need to work out when when we move off super early bird etc...

-- 
Phil Lang - Digital Production Editor
@ODIHQ | thodi.org
@langphil | 0741 44 63047

On 4 June 2015 at 13:58:51, Andrea (notifications@github.com) wrote:

and the full launch?

**Comment by greenreveller** [comment]
Thanks Phil. When will we begin marketing the tickets? I'm just trying to
ascertain when this tech login issue needs to be resolved so that we can
send signup links to people who have bought membership alongside their
summit tickets.

Andrea

Andrea Cox
Membership Manager
@greenreveller <https://twitter.com/greenreveller> @ODIHQmembers
<https://twitter.com/ODIHQmembers>

The Open Data Institute <http://www.theodi.org/>
Tel +44 (0) 7855 456 002

**Comment by langphil** [comment]
Hey Clara, 

Myself and Keren need to sit down and discuss this. 

I will let you know.

-- 
Phil Lang - Digital Production Editor
@ODIHQ | thodi.org
@langphil | 0741 44 63047

On 4 June 2015 at 14:54:38, Andrea (notifications@github.com) wrote:

Thanks Phil. When will we begin marketing the tickets? I'm just trying to
ascertain when this tech login issue needs to be resolved so that we can
send signup links to people who have bought membership alongside their
summit tickets.

Andrea

Andrea Cox
Membership Manager
@greenreveller <https://twitter.com/greenreveller> @ODIHQmembers
<https://twitter.com/ODIHQmembers>

The Open Data Institute <http://www.theodi.org/>
Tel +44 (0) 7855 456 002

**Comment by pezholio** [comment]
@greenreveller I'm picking this up this week for you. Got a couple of questions:

* I'm assuming we'll want to add a "Pay by" option to the signup form
* If so, do we want this for corporate members only (i.e. not individuals)
* If we only want the option to show for corporates, do we want to assume that any individuals added through Capsule will be paying via invoice?
* Also: are we invoicing through Xero?

**Comment by greenreveller** [comment]
Great stuff Stuart. To your points: 
a) Where possible we would like to encourage organisations (SMEs & Corporates) to pay by credit card. Could there be some kind of hidden option whereby the usual signup form doesn't give the option for invoicing but we have a URL which we can send to specific organisations where the option is revealed? 
b) The invoice option will only be for organisations (SMEs & Corporate members). 
c) Ee don't want to let individual supporters pay by invoice at all (and don't want to add them manually at all ideally). At the moment when we are adding supporters manually to capsule it is linked to issue 3.a of this document: https://docs.google.com/document/d/1hSK2vY7S5aQ6LE8LpO7-_gA4GclAEbao0GWU8TuHaKM/edit
d) We are invoicing through Xero

**Comment by pezholio** [comment]
@greenreveller Cool, most of that work is done now I reckon. Just a process issue now I think. So, what will happen now is the user will sign up, go to the thanks page, and a draft invoice will be generated. Once you've taken the invoice out of draft, and it's been paid, you can set the user to `active` in Capsule and the changes will be reflected in the Member Directory once the sync runs.

**Comment by greenreveller** [comment]
@pezholio ah, i have just foreseen an issue re your point 3. 

If summit attendees buy individual membership via Eventbrite (which is looking likely) then we will need to be able register these new individual supporters manually on the directory (without sending them to chargify) and send them a welcome email which sends them straight to their profile page. 

@alisonwalters would we need to send individuals an invoice via Xero (with a 100% discount) in this instance or would the receipt from Eventbrite suffice? Would be great if we didn't have to faff around sending them individual invoices.

**Comment by greenreveller** [comment]
@langphil can you personalise the emails which particular ticket holders get on Eventbrite e.g. can you send a different 'thank you for your purchase' email to summit attendees who are purchasing membership with their summit ticket and those who are not?

**Comment by langphil** [comment]
As far as I am aware, yes. 

You can also redirect to specific landing pages after payment has been made, if that helps at all. 

Let me check now.

-- 
Phil Lang - Digital Production Editor
@ODIHQ | thodi.org
@langphil | 0741 44 63047

On 9 June 2015 at 12:25:53, Andrea (notifications@github.com) wrote:

@langphil can you personalise the emails which particular ticket holders get on Eventbrite e.g. can you send a different 'thank you for your purchase' email to summit attendees who are purchasing membership with their summit ticket and those who are not?

**Comment by langphil** [comment]
It seems we can’t tailor email responses or landing pages for individual ticket types. There is only the option to create one type that applies to all sales. 


-- 
Phil Lang - Digital Production Editor
@ODIHQ | thodi.org
@langphil | 0741 44 63047

On 9 June 2015 at 12:27:10, Phil (phil.lang@theodi.org) wrote:

As far as I am aware, yes. 

You can also redirect to specific landing pages after payment has been made, if that helps at all. 

Let me check now.

-- 
Phil Lang - Digital Production Editor
@ODIHQ | thodi.org
@langphil | 0741 44 63047

On 9 June 2015 at 12:25:53, Andrea (notifications@github.com) wrote:

@langphil can you personalise the emails which particular ticket holders get on Eventbrite e.g. can you send a different 'thank you for your purchase' email to summit attendees who are purchasing membership with their summit ticket and those who are not?

**Comment by alisonwalters** [comment]
Hi Andrea,
The invoice would need to come to Xero for the summit attendance part- the
invoice for the summit tickets needs to be split into 2 lines, summit
attendance and membership. Lets discuss how this will work on the call.

thanks

Ali

**Comment by greenreveller** [comment]
Hi @pezholio. Have tested the URL for members signing up by invoice. 

The registration is fine, links to capsule are fine. But when the invoice is coming through to Xero the description field has: 
ODI Supporter (GS660BY) [Non Commercial] (card payment)
PAID BY CREDIT CARD; reference

The '(card payment)' and 'PAID BY CREDIT CARD; reference' need to be removed from all invoice payments otherwise Finance team won't know to send the invoices out. 

Does that make sense?

**Comment by pezholio** [comment]
Ah, gotcha. I'll have a look at that.

**Comment by greenreveller** [comment]
Also could you add a PO number field?
Cheers

**Comment by alisonwalters** [comment]
thanks both

**Comment by greenreveller** [comment]
Hi @pezholio we've had a supporter (university of essex, they guy's email is: vsena@essex.ac.uk) sign up using the invoice link. They say they 'have filled in the form but cannot enter the account' by which I think they mean that they can't go on to enter their directory entry profile. 

I can't see them appearing in Capsule or in Xero - can you see if there's a reason why they haven't come through?

**Comment by pezholio** [comment]
I've fixed that now. Seems that the code that checks if they're invoiced members isn't working, so it didn't send them to Capsule or make them active. I'll look into this now.

**Comment by pezholio** [comment]
I'm very confused. I can't replicate this locally. Everything works as expected. I'm going to make a test account on the live system and see what happens.

**Comment by pezholio** [comment]
Yeah, this worked in the live system too, so I'm baffled.

**Comment by greenreveller** [comment]
So now Essex has come through normally (in capsule and in xero). I can't yet see your test sign-up come through on Capsule / Xero (could be a timing thing?)

**Comment by pezholio** [comment]
Oh, I deleted them :)

**Comment by greenreveller** [comment]
Great stuff. Not completely clear on what you're baffled on though :/

**Comment by pezholio** [comment]
I don't know why it didn't work for Essex. Seems to be working fine :cry:

**Comment by greenreveller** [comment]
how bizzare - well, i have another one to try right now so let's see how
that does

Andrea

Andrea Cox
Membership Manager
@greenreveller <https://twitter.com/greenreveller> @ODIHQmembers
<https://twitter.com/ODIHQmembers>

The Open Data Institute <http://www.theodi.org/>
Tel +44 (0) 7855 456 002

**Comment by greenreveller** [comment]
Hi @pezholio, for people who are paying for membership via invoice we are still getting the invoices displaying in Xero as marked as paid e.g. 

ODI Supporter (GS660BY) Non Commercial
PAID BY CREDIT CARD; reference

The 'PAID BY CREDIT CARD; reference' needs to be removed from all invoice payments otherwise Finance team won't know to send the invoices out.

Cheers,
