### ISSUE TITLE
Create duplicate page of theodi.org/postcard at theodi.org/postcards

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#415]

**Comment by Floppy** [comment]
Presumably this could be a redirection?

**Comment by greenreveller** [comment]
yes indeed :)

Andrea

Andrea Cox
Membership Manager
@greenreveller <https://twitter.com/greenreveller> @ODIHQmembers
<https://twitter.com/ODIHQmembers>

The Open Data Institute <http://www.theodi.org/>
Tel +44 (0) 7855 456 002

**Comment by Floppy** [comment]
done!

**Comment by greenreveller** [comment]
Fab, thanks James
