### ISSUE TITLE
Allow summit attendees to purchase membership alongside summit ticket - ASAP

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#418]
Summit attendees are purchasing tickets through Eventbrite. 
They need to have the option to buy individual or organisational supporter membership alongside their summit ticket. 
Membership team needs to ensure that new supporoters are registered in member directory and on Capsule
Membership team would ideally like to get new members to enter their credit card details into Chargify so that they can charge new members automatically for y2 membership
Finance team needs to make sure that money is allocated from the summit ticket purchase to membership. 
Finance team needs to make sure that new members are only counted once in their systems and not twice (e.g. via Xero AND Chargify)
New members want to have as easy a sign-up process as possible for summit and membership 

@pezholio @alisonwalters @langphil

**Comment by pezholio** [comment]
Right, so the easiest option is I think:

* User buys membership / ticket combo on Eventbrite
* Membership team add user's details and membership tag manually to Capsule
* Member Directory picks up the new member and sends an email

I originally thought that the invoice was generated when this happens, but on reviewing the code, it looks like it isn't, so this solves our problem.

**Comment by greenreveller** [comment]
Pros
Limits number of user clicks to get summit registered and member registered
Easiest way to get member numbers up in the short-term
Eventbrite will do the counting of membership revenue and summit revenue, no duplication in Xero

Cons
Membership team will have to continue manually encouraging members to add their credit card details to our Chargify until at least November 2016
Potentially significant drop off of member sign-ups from our systems at y2 renewal

Questions
@pezholio you mentioned yst that we would possibly able to automate member sign-ups via Eventbrite data. @langphil Will we able to capture/export the following fields of data from Eventbrite? 
- First name
- Last name
- date of purchase
- email address
- membership level type (supporter [SME/Corporate], individual)

and for those who are selecting supporter membership [SME/Corporate] could we collect and export the following data:
- size (<10, 10-50, 51-250, 251+)
- sector (from list of sectors: https://docs.google.com/document/d/18XIZ2AY_pnpu-Rzj2nuoLirfPdFzeEGhh3keiwdIinE/edit#heading=h.3foxn8ue2j9f)

@alisonwalters I presume you're going to have to set up all the new summit ticket tiers in Xero and Stripe for all these tickets pre-testing?

**Comment by greenreveller** [comment]
Hi all, with the pressure to get summit tickets live just a few things we need to sort from a membership pov: 
@pezholio - will it be possible to automate membership sign-ups from Eventbrite data? If yes, when's it likely we could we get that live?
@langphil - as mentioned, I've listed the data fields we need for member sign-up above - would it be possible to capture these fields in Eventbrite (for the appropriate options?)
@alisonwalters - any finance things we need to consider before proceeding?
