### ISSUE TITLE
Signal Noise not showing directory entry 

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#419]
GH9206SP - directory entry in CApsule (and ticked active) but not on directory.theodi.org. Meeting with them tmrw - would be amazing if we can get live before tmrw pm.

**Comment by pezholio** [comment]
Seems to be showing fine now - https://directory.theodi.org/members/GH9206SP

**Comment by greenreveller** [comment]
weird. they were ticked as active in capsule. i unticked them, saved, then ticked them again. Seems to have done the trick. Gah! Capsule!
