### ISSUE TITLE
Show coupon code field for Individual Supporter registration page 

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#420]
Please can we show coupon code field to Individual Supporter registration page on Chargify? We need this for a promo for an event on Saturday. I think that this is controlled by our member directory code rather than by Chargify?
@pkqk 

I realise there may be implications for how we run the finance reports as a result of this but will come to this later!

**Comment by pkqk** [comment]
So you want people to be able enter a discount code on the initial registration page. (e.g.  https://directory.theodi.org/members/new?level=individual)

or on the chargify page?

If it's on the member-directory page then yeah we need to add the ability to show the `coupon` input field. The code should already deal with the rest of the flow.

**Comment by greenreveller** [comment]
I want the easiest option!

**Comment by pkqk** [comment]
Done by unhiding the coupon on the individual signup chargify page.
