### ISSUE TITLE
Improve UX for node individual Supporter sign-ups - ASAP

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#421]
Deadline: end of August

As a membership manager I want to be able to distinguish between members who have signed up for organisational or individual membership through an ODI node in my CRM system. Ideally I want to have each member who has signed up through a node tagged in Capsule as ‘nodemember’ and also by the specific node which they are affiliated to e.g. ‘ODILeeds’. In order for this to happen I would need to collect this data in the member registration form (initially for individuals and in 2016 for organisations).

As an ODI node I want to be able to track sales of Individual Supporters which have come via my bespoke Wordpress site (e.g. leeds.theodi.org). Currently I encourage individual supporters who sign up using my site to click on a generic link e.g. https://directory.theodi.org/members/new?level=supporter&origin=ODICHICAGO. This allows the ODIHQ finance team to track which sign-ups came via which node (and pay us revenue accordingly). 

As a node I would also like to receive a regular update of all of the members which have been signed up via my node (so that I can estimate how much revenue I expect to generate each quarter via membership). 

As a node a potential problem with this is that a lot of my users could drop away from my node specific membership page before they purchase membership. This might be so that they can browse my node site or the ODIHQ site to understand more about the membership offering. I can't be confident that people who are 'my' sign-ups are getting recorded as such on ODIHQ systems.

We need to improve UX on member signup pages to avoid people clicking away from the registration pages: 
- Add headline member benefits to the top of the signup page e.g. As an Individual Supporter you'll get 20% discount on training - LinkedIn etc....
- Add link back to the membership page for more details that opens in a new window
- Longer-term, ensure that the node referral is more persistent (through cookies?) 

We also need to consider whether the using a bespoke link to track node signups is the best way to facilitate node membership sales. Perhaps a system whereby users can select a node which they are affiliated with on a drop down list on the main membership registration page would be better?

* [x] Add `node` dropdown field to the signup form for individual memberships
* [x] Signups via a node should be tagged "nodemember" and the individual node i.e. "ODILeeds"
* [x] Set session cookie when visiting via the node's link so we can remember the value if they navigate away

**Comment by jordelver** [comment]
@greenreveller 

> As an ODI node I want to be able to track sales of Individual Supporters which have come via my bespoke Wordpress site (e.g. leeds.theodi.org). Currently I encourage individual supporters who sign up using my site to click on a generic link e.g. https://directory.theodi.org/members/new?level=supporter&origin=ODICHICAGO. This allows the ODIHQ finance team to track which sign-ups came via which node (and pay us revenue accordingly).

Are you happy to continue using a URL like `https://directory.theodi.org/members/new?level=supporter&origin=ODICHICAGO` as long as it solves the drop out problem where signups are not correctly attributed to the node?

**Comment by greenreveller** [comment]
Yes it could work that way if the drop out problem was fixed. But I'd also like to consider whether actually having a system whereby users can select a node which they are affiliated with on a drop down list on the main membership registration page would be better. As we scale I think this would help us and the nodes. 

It would be good to explore how that might work on the back end and if we could assign a tag in Capsule to show if users are affiliated to a particular node. (That's useful information for the organisation to have captured in the CRM system).

**Comment by jordelver** [comment]
Yes, that's a good idea. I didn't realise you meant adding a dropdown to the signup form :+1: 

A combination of both is probably a good idea. So, if you come via the _special_ URL then the node dropdown would be auto-selected.

**Comment by jordelver** [comment]
> - Add headline member benefits to the top of the signup page e.g. As an Individual Supporter you'll get 20% discount on training - LinkedIn etc....

Could you show me where this needs to go, please? And supply the content.

> - Add link back to the membership page for more details that opens in a new window

Where should this go?

**Comment by greenreveller** [comment]
The text for headline member benefits are: 

	•	Use the ODI [[Supporter badge](https://drive.google.com/a/theodi.org/file/d/0B3eBuwLRqgy1OFllV2hpT3pRRW8/view)] on your website
	•	Join our global networks on [[LinkedIn](https://www.linkedin.com/grp/home?gid=5161407)] and [[Twitter](https://twitter.com/ODIHQmembers)]
	•	Claim 20% discount on [[ODI Training](http://theodi.org/courses)]
	•	Receive our monthly newsletter
	•	Get priority notifications and discounts on [[ODI events](http://theodi.org/events)]

I was thinking of putting this text as a line along the top of the registration page: https://directory.theodi.org/members/new?level=individual

Perhaps just below the blue banner and above the text 'We're delighted...'. I’m not sure of the best way of displaying this. In a list or as a line of text? What do you think? 

Re the link to the membership page - let's talk about this at 9.50

**Comment by greenreveller** [comment]
The list of nodes (19) is: 
Athens

Belfast

Buenos Aires

Cairo

Chicago

Devon

Dubai

Gothenburg

Hampshire

Leeds

Osaka

Paris

Queensland

Rio

Seoul

Sheffield

St Petersburg/Moscow

Toronto

Trento

**Comment by greenreveller** [comment]
Text which describes nodes (to pop out if you hover over an info button - or sth similar)

ODI Nodes are local franchises of the ODI who focus on promoting open data via learning and networking

**Comment by jordelver** [comment]
Great, thanks for both :+1:

**Comment by jordelver** [comment]
> Perhaps just below the blue banner and above the text 'We're delighted...'. I’m not sure of the best way of displaying this. In a list or as a line of text? What do you think?

I added this into the page but I think it takes up too much room for the signup page. The main focus should be to signup. The benefits should already have been sold by this point.

I think we should split this item out into a separate ticket so we can handle it later. What do you think @greenreveller ?

**Comment by greenreveller** [comment]
yes, see what you mean - think we can close headline member benefits and link back to membership page tickets. The drop-down node list in the registration section is the main thing here

**Comment by jordelver** [comment]
Great, thanks :+1:

**Comment by jordelver** [comment]
This is live now @greenreveller. Do you close the issues once you've tested?

**Comment by greenreveller** [comment]
Yep :)

Andrea

Andrea Cox
Membership Manager
@greenreveller <https://twitter.com/greenreveller> @ODIHQmembers
<https://twitter.com/ODIHQmembers>

The Open Data Institute <http://www.theodi.org/>
Tel +44 (0) 7855 456 002

**Comment by greenreveller** [comment]
Cool - have tested with CC payment and everything is be showing up correctly in Capsule and user is receiving correct welcome emails etc.

The invoice which has come through to Xero is showing the incorrect amount though (£108 + VAT) rather than £90 + VAT. However, as per discussions with @alisonwalters we will be doing away with the link between Chargify and Xero so I am not sure if this is a problem. Can you confirm @alisonwalters ?

Cheesr,
