### ISSUE TITLE
Regularly fetch coupon/pricing info from chargify

### ISSUE THREAD

**Issue by pkqk** [theodi/member-directory#422]
Some of the information is fetched from Chargify on start up.

If a coupon is added and the site has not been deployed or otherwise restarted since then it won't pick up the new info.

**Comment by greenreveller** [comment]
NB this needs to be tested for new ODI Leeds coupons to check that they are recognised. 

We may need also to display the discount code field on the sign-up pages to ease registration.

**Comment by jordelver** [comment]
We should think about https://github.com/theodi/member-directory/issues/387 in conjunction with this one

**Comment by Floppy** [comment]
this code is all gone now
