### ISSUE TITLE
VAT not being charged on SME Supporter £540 product in Chargify

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#424]
From Steph Dunstan: We have subscriptions set up in Chargify for the product "(ODI Organisation Membership) Supporter (annual)" at a value of £648 including VAT (Net price £540). 

There have been instances in the past month where subscriptions for this product have been charged £540 only and not the VAT component. 

A query was raised with Chargify. It was explained there are two scenarios currently occurring: 

1. For the members Scraperwiki & 100% Open, it appeared the 'billing address' (on the credit card profile) used to calculate tax was missing everything but the postal code. Chargify have advised the full billing address needs to be collected in order for VAT to be charged. Andrea checked the product details and in the produce the field "require billing details" had been ticked. 
--> Are we able to confirm how these subscriptions are not being charged for VAT for this product despite the billing details being required? 

2. For members Mydex and import.io it appeared the credit card was updated after the initial charges took place, so it is possible the billing information was missing during signup and thus no VAT collected. This has been remedied by the credit card details being updated and the upcoming renewal shows that VAT will be charged on the next billing. 

It seems that:
a) As long as the full billing details are entered when the credit card details are updated (before the billing date) VAT will be collected accordingly; and
b) If there is a component of the billing details missing, VAT will not be collected. 

Chargify enquired whether we are requiring the full billing address during signup. Are we able to confirm this? 

@pkqk

**Comment by alisonwalters** [comment]
Hi,
That's really helpful, thank you for getting to the bottom of it.
we cannot have a membership progressing without the correct VAT being
charged. We will be liable to huge penalties from HMRC.
Can we make it so that it is not possible to progress to payment without
the required fields being filled?

thanks

ali

**Comment by pkqk** [comment]
For every product we have in the Chargify system it has require 'billing address' checked.

When I was testing it it didn't let the transaction progress unless the postal code was filled in.

**Comment by greenreveller** [comment]
awaiting Chargify help desk response on this issue
