### ISSUE TITLE
Please delete Surrey County Council details from member directory 

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#431]
They have got halfway through a sign-up but then decided to pay by invoice (which they won't be able to do as the email is already registered). Cheers,

**Comment by pezholio** [comment]
Done!

**Comment by greenreveller** [comment]
Surrey CC have since tried to sign up by using the invoice link but they are not able to do so as the organisation name still remains taken ( even though I thought we had deleted). See below: 

Hi Patrik, 

I've been using the web form you provided previously (https://directory.theodi.org/members/new?level=supporter&invoice=true) but am now denied access (organisation name already taken!).  Nor can i log in as a member yet as my email is not recognised.   

How is best to proceed so we can sign them up asap?
@pkqk any chance can you help out in @pezholio absence?

**Comment by Floppy** [comment]
@greenreveller I'll see if I can take a look between meetings or over lunch.

**Comment by greenreveller** [comment]
Cheers James

**Comment by greenreveller** [comment]
@Floppy any luck?

**Comment by Floppy** [comment]
Done; there are two models in the DB that need removing, I think we only killed one before. Should work happily now.
