### ISSUE TITLE
Summit + membership sign-up failing - needs fix ASAP

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#437]
@langphil  tested signing up for individual supporter sign-up and summit ticket combined yesterday via Eventbrite.

As per #418 Stuart had built automated system so that when users buy a combined ticket the directory automatically tags them as a member in directory and capsule and triggers a welcome email (so we don't have to add each new user manually).

I can see Phil's sign-up in Eventbrite but I haven't seen anything come through on capsule or any automated welcome email yesterday or today.

@Floppy @pezholio  - We really need this to be working by EOP today before summit tickets go on sale after Awards - possible for someone to have a look at?

**Comment by Floppy** [comment]
*cries a little*

**Comment by Floppy** [comment]
With @pezholio and @pkqk out, that's down to me to look at. I'll drop everything and get on it.

**Comment by greenreveller** [comment]
Thanks James

**Comment by Floppy** [comment]
The job is sitting in the queue, but is being killed without completing correctly. I have absolutely no idea why right now. It's strange.

**Comment by greenreveller** [comment]
gah.... grrrr...

Andrea

Andrea Cox
Membership Manager
@greenreveller <https://twitter.com/greenreveller> @ODIHQmembers
<https://twitter.com/ODIHQmembers>

The Open Data Institute <http://www.theodi.org/>
Tel +44 (0) 7855 456 002

**Comment by Floppy** [comment]
There appears to be a massive memory leak in the SendSignupToCapsule code, which is killing the box and the process whenever it runs. Still investigating...

**Comment by langphil** [comment]
Just received an email in my inbox. 

Proud to say, that I’m now and ODI individual supporter and I’m attending the ODI 2015 Summit. 

-- 
Phil Lang - Digital Production Editor
@ODIHQ | thodi.org
@langphil | 0741 44 63047

On 8 July 2015 at 14:43:15, James Smith (notifications@github.com) wrote:

There appears to be a massive memory leak in the SendSignupToCapsule code, which is killing the box and the process whenever it runs. Still investigating...

**Comment by greenreveller** [comment]
Hooray :)

Andrea

Andrea Cox
Membership Manager
@greenreveller <https://twitter.com/greenreveller> @ODIHQmembers
<https://twitter.com/ODIHQmembers>

The Open Data Institute <http://www.theodi.org/>
Tel +44 (0) 7855 456 002

**Comment by greenreveller** [comment]
james - is it possible to get members@theodi.org cc'd in on those auto welcome emails so that we can cross-check if people are receiving them going forwards?

**Comment by greenreveller** [comment]
nb @Floppy will the changes you've made today apply to SME supporter + summit package and corporate supporter + summit package (as well as individual supporter package)?

**Comment by Floppy** [comment]
That's fantastic! I just fixed the issue so it's good to see the rest of the system worked as expected. It's having trouble saving the membership ID back into CapsuleCRM, so I'll fix that as well before I close this, but that's lower priority I think. @greenreveller yes, it should do, it was a generic problem that applied across both. Can you add ccing as a separate ticket? I'll see if I can add it in quickly.

**Comment by greenreveller** [comment]
Done! #439 Good work James :)

**Comment by Floppy** [comment]
OK, this is all done and tested now. Working. Yay!
