### ISSUE TITLE
Potential member is using coupon code URL but discount is not being applied

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#438]
They have code 'JUNEDEAL' which is a non-expiring code set up on Chargify. Users use URL https://directory.theodi.org/members/new?level=supporter&coupon=JUNEDEAL to be eligible for this discount. We have tested and it works fine.

However, when this user clicks through to the payment pages the code is not being applied. 

We think that this *may* be because they have created a member profile and password but not completed registration first time around. Then when they are signing in again the coupon code is not getting applied (they are being redirected to https://directory.theodi.org/members/new?level=supporter)

One potential solution would be to remove Pivotal account from member directory and start over?(jnagy@pivotal.io). We have their details so we can process the registration for them. @Floppy 

Cheers,

**Comment by greenreveller** [comment]
Hi @Floppy @pezholio - will you be able to have a look into this? Pivotal (potential Supporter) are on our case - risk of losing this sale unless we can get this fixed. Ta,

**Comment by Floppy** [comment]
I'll remove the old account and you can do it manually from there...

**Comment by Floppy** [comment]
This, btw, should be possible through the member directory admin interface, but I'm completely unsure if that's working any more.

**Comment by Floppy** [comment]
Yeah, google changed everything and that doesn't work no more. Sadface.

**Comment by Floppy** [comment]
OK, this account is removed now, you can recreate it at will.

**Comment by greenreveller** [comment]
Cheers - should we wait a couple of hours for the member directory to
refresh or are we good to add them now?

Andrea

Andrea Cox
Membership Manager
@greenreveller <https://twitter.com/greenreveller> @ODIHQmembers
<https://twitter.com/ODIHQmembers>

The Open Data Institute <http://www.theodi.org/>
Tel +44 (0) 7855 456 002

**Comment by Floppy** [comment]
This should be OK to go now.
