### ISSUE TITLE
Cc members@theodi.org into auto welcome emails generated via summit + membership signups

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#439]

**Comment by Floppy** [comment]
Interestingly, according to the code and the mandrill sent records, this is already the case. Could you check your spam filters quickly see if it's in there?

**Comment by Floppy** [comment]
To be clear; I *know* from Mandrill that Phil's welcome email was bcc'ed to the members@theodi.org address... so if it's not appearing, it's being filtered somewhere downstream.

**Comment by greenreveller** [comment]
checked spam, nothing there

Andrea

Andrea Cox
Membership Manager
@greenreveller <https://twitter.com/greenreveller> @ODIHQmembers
<https://twitter.com/ODIHQmembers>

The Open Data Institute <http://www.theodi.org/>
Tel +44 (0) 7855 456 002

**Comment by Floppy** [comment]
How very odd...

**Comment by greenreveller** [comment]
To keep an eye on as we start selling summit & membership packages

**Comment by greenreveller** [comment]
I can see from Eventbrite that one individual supporter + summit ticket purchase was made this morning by Gerald	Milward-Oliver. Haven't yet seen any welcome email come through via member directory. 

@pezholio @jordelver - Can you check to see if email has been generated?

**Comment by jordelver** [comment]
I'd need access to Mandrill to check @greenreveller. @floppy can you sort out access to that for me, please?

**Comment by pezholio** [comment]
Done! :+1:

**Comment by jordelver** [comment]
@greenreveller those emails were both delivered according to Mandrill.

![2015-08-21 at 09 36](https://cloud.githubusercontent.com/assets/6588/9404580/b93e826e-47e8-11e5-8bc6-8bffd008bebf.png)

Both of those emails have the same membership id in them. 

Can you spot anything obviously wrong?
