### ISSUE TITLE
Rogue Corporate Supporter signup/invoice?

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#442]
Corporate Supporter 'Dave McDave' (!) appeared in Xero (and was sent a welcome email) but no credit card payment was made. Member ID EG2926TC.
@Floppy Do you know if this is a test account? Or bug?

**Comment by Floppy** [comment]
Hmmm. Let me check the test code. It does *seem* like a fake :)

**Comment by Floppy** [comment]
Nope, this isn't from our test data, and I certainly didn't enter it manually. I also can't find it in the job history, and he doesn't appear to be in Capsule either. How very strange. The email address entered was davemdave@dave.com, which hard bounced, so there's nothing real here at all. Was it marked as to be invoiced in Xero, because that might make sense if it was...

**Comment by pezholio** [comment]
That sounds like the kind of test data I'd enter

**Comment by greenreveller** [comment]
I can see a 'Dave1' invoice for £2,200 in Xero for that email yes. So what
do we need to do here (aside from delete draft invoice)?

Andrea

Andrea Cox
Membership Manager
@greenreveller <https://twitter.com/greenreveller> @ODIHQmembers
<https://twitter.com/ODIHQmembers>

The Open Data Institute <http://www.theodi.org/>
Tel +44 (0) 7855 456 002

**Comment by Floppy** [comment]
There's not really a lot I can tell here, because nothing seems to show. Can we remove the draft invoice and just see if it ever happens again? I have honestly no idea what's happened here...

**Comment by greenreveller** [comment]
We've deleted the invoice in Xero. We can delete contact in Capsule too but as per our conversation last week i think you also need to delete the dependencies in the directory?  Let us know if we should go ahead and delete in Capsule. Cheers,

**Comment by greenreveller** [comment]
also to that end do you need to delete Phil's indidivudal supporter test account in member directory as well?

**Comment by Floppy** [comment]
Yes, I can clear those out.

**Comment by Floppy** [comment]
Removed Phil and Dave.
