### ISSUE TITLE
Delete Networked Planet from Member Directory

### ISSUE THREAD

**Issue by PatrikWagner** [theodi/member-directory#444]
They got half way through registering but decided to pay via invoice - now the invoice link won't work as they're already in the system.

Cheers! @pezholio @Floppy

**Comment by Floppy** [comment]
Argh. There's obviously something about our signup flow that's making this happen all the time...

**Comment by Floppy** [comment]
Removed them. Should be OK to sign up again now.

**Comment by PatrikWagner** [comment]
Cheers! Yeah I think there must be something around the signup flow.

**Comment by Floppy** [comment]
Looks like @greenreveller identified it nicely in #445
