### ISSUE TITLE
 Members getting trapped in Credit card payment system when they want to pay by invoice

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#445]
As an employee of an organisation who is trying to sign up as a member I go through registration (and along the way I create a password for my organisation) until I reach payment page. At this point I realise have to pay by credit card. I don’t have a credit card to pay with so I contact the sales rep at the ODI to pay by invoice. 

I am sent a link by which to pay via invoice. When I click on this link and sign in again I am directed to the CC page. This is because I have already created a profile for myself on the member directory by setting up a password earlier. 
At this point the membership team and tech team need to delete my organisation and associated dependencies from Capsule and the member directory before I can use the invoice link to sign in. 

I don’t want to have to go through this confusion when I am signing up!

* [x] Fix problem where the member cannot complete the signup
* [ ] Add link to the invoice link from the payment page

**Comment by Floppy** [comment]
Fantastic, thanks for identifying this workflow problem so clearly. Brilliant :)

**Comment by greenreveller** [comment]
I think this workflow problem also impacts when a potential member signs up using a URL with a coupon (discount) pre-loaded and they navigate away from the page. When they come back to the page using the same URL they cannot anymore see the discount/coupon applied.

**Comment by jordelver** [comment]
@greenreveller 

> I am sent a link by which to pay via invoice. 

What does this link look like? How is it created?

**Comment by greenreveller** [comment]
https://directory.theodi.org/members/new?level=supporter&invoice=true

This was a system created a couple of months ago by @pezholio see #413

**Comment by jordelver** [comment]
Great, thanks @greenreveller

**Comment by jordelver** [comment]
As well as fixing the original issue, would it also make sense to add a link to the credit card payment screen if the package is supporter? Something like "Would you rather pay by invoice?" that links directly to the link above. 

Are people dropping out on the Chargify page or before? It won't stop all of the manual intervention, but might help. What do you think @greenreveller?

**Comment by greenreveller** [comment]
Yes that's a great idea. Anecdotally (no Google Analytics on this) people are dropping off when they reach the Chargify page and realise that credit card is the only payment option. 

We could give people the option on the previous page (which confirms the amount of the membership) to pay either by invoice or credit card and then direct them to the correct page accordingly. 

One thing to bear in mind is that https://directory.theodi.org/members/new?level=supporter&invoice=true is the same as the starting page https://directory.theodi.org/members/new?level=supporter for credit card payments. So if you redirected to the invoice URL at the Chargify page (or the previous page) you would be asking someone to enter the same data as they have already entered on https://directory.theodi.org/members/new?level=supporter. Does that make sense?

**Comment by jordelver** [comment]
Ah, I think I understand. Perhaps we could just avoid all this kerfuffle by offering invoice as a payment type but make sure to emphasise credit card in the UI? What membership types is invoice available to again?

**Comment by greenreveller** [comment]
Yes, that sounds like it would be simpler. Invoice is available for organisational members for both tiers: SME/non-profit
Corporate

It's only credit/debit card payment for individual supporters. 
NB individual supporter sign-up page is here: https://directory.theodi.org/members/new?level=individual

**Comment by jordelver** [comment]
Ok, cool. I'll have a think about how to implement.

**Comment by jordelver** [comment]
This is ready for testing @greenreveller
