### ISSUE TITLE
Drop down menu options for organisation type in sign up form need to change

### ISSUE THREAD

**Issue by BertLewis** [theodi/member-directory#446]
Hello, we've had feedback from a new member (Nquiringminds) that the options in the drop down menu for organisation type in the sign up form for Membership are a bit confusing. Could we please change them to say Corporate Supporter and SME/ non-profit Supporter (instead of Corporate and non-profit/ government). Many thanks! (I hope this all makes sense).

**Comment by greenreveller** [comment]
Change drop-down field on https://directory.theodi.org/members/new?level=supporter from 'Nonprofit / Government' to 'SME / Nonprofit / Government'
