### ISSUE TITLE
Having to tick 'active' in Capsule for an org member to make their Directory profile live

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#448]
@pkqk had made this no longer necessary a few months back. Seems now to be necessary again. Ideally would not like this manual step in registration process.

**Comment by Floppy** [comment]
Strange that that's come back all by itself... hrm.

**Comment by pkqk** [comment]
Someone fed the gremlins after midnight.

**Comment by greenreveller** [comment]
In an org profile click on 'edit' e.g.: 
![image](https://cloud.githubusercontent.com/assets/5023266/9462098/05a987f0-4b0b-11e5-9efb-a7802a5d8fbc.png)
Then 'active' box is on the right hand side
![image](https://cloud.githubusercontent.com/assets/5023266/9462102/0cec71bc-4b0b-11e5-84c2-fd66982417ef.png)

**Comment by jordelver** [comment]
Ok, thanks :+1:

**Comment by jordelver** [comment]
After getting my head around this I remain confused @greenreveller ;)

The way it currently seems to work for both credit card and invoiced customers is that their directory entry is made live as soon as they complete the signup process. This is not how I understood it was supposed to work?

My current theory is that members are made active immediately. As such, they will appear in the directory. But, as soon as the Capsule Sync runs (I think every 15 minutes), they are made inactive. I'm still investigating that.

**Comment by jordelver** [comment]
My theory is correct. The members is active and then as soon as the Capsule Sync runs, it's made inactive again. I think I know where to fix, but will wait until I speak to you @greenreveller

**Comment by jordelver** [comment]
Also, I meant to say, does this just affect members created via Capsule?

**Comment by greenreveller** [comment]
Let's go with making all organisations live on the Member Directory (no matter whether they have completed company profile, social media details etc).

**Comment by jordelver** [comment]
Hi @greenreveller I'm a bit confused by this. Now that we make members live straight away is this still a problem?

**Comment by greenreveller** [comment]
Wait until new member signs up to check this

**Comment by greenreveller** [comment]
@greenreveller to keep an eye on this over the next 2 weeks
