### ISSUE TITLE
New member GeoWise's Directory Entry has disappeared

### ISSUE THREAD

**Issue by BertLewis** [theodi/member-directory#458]
Hiya, GeoWise (PZ0603JE) have been in touch to say their member entry has disappeared from the Directory. They'd like to install the ODI badge but also wanted to know if they can anchor tag our logo to their directory entry (would that be possible?). Thanks!

**Comment by greenreveller** [comment]
@BertLewis did you tick active in Capsule to make it live when you were registering? 

not possible to add any logo to their member directory entry (only partners/sponsors can do)

**Comment by BertLewis** [comment]
@greenreveller apologies, I really thought I had (and had checked that they were up) but I went back to be sure and it wasn't active so that should resolve it. 
Re logo: they don't want to add a logo to our website, they want to know if it's possible to embed our logo on their site with an anchor tag to the directory listing (rather than a simple link taking them to the directory listing). This is partly because the script for the badge embed is not working for him. I don't understand the technical details fully but thought worth asking about the anchor tag. If I know what to ask, I can go back to him for more details.

**Comment by greenreveller** [comment]
ah ok, the badge should anchor back to their member directory entry already e.g. see badge at bottom of http://www.networkedplanet.com/

am i understanding you correctly?

**Comment by BertLewis** [comment]
Mmm, no, I don't think so but I don't fully understand him either - he also wanted to know if he could link to the ODI homepage instead of directory entry so I don't think it's the same as the normal linked embedded icon. hashtag-confused :/
