### ISSUE TITLE
4 individual supporters registered in July/August. Members@theodi.org not getting cc'd into their welcome emails

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#459]
We normally get cc'd into the auto-generated 'welcome to the ODI' email and the Chargify statement emails when individual supporters register. members@theodi.org need to be cc'd into these two emails so that we know when a supporter signs up.

For the last 4 Individual Supporrters we have received neither email. (We have been receiving emails correctly for all organisation Supporters). This has affected the accuracy of our end of month figures. 

@Floppy - this possibly relates to #439 ? 

* [x] Add a test for the BCC to members@theodi.org to catch future regressions
* [x] Add tests to make sure the email is being sent in all the places it should be

**Comment by jordelver** [comment]
Need to make sure the email is being sent via all signup routes

**Comment by jordelver** [comment]
I've tested these four scenarios manually on my local machine and the email is sent in all cases:

* Individual signup with credit card payment (`?level=individual`)
* Individual signup with invoice (`?level=individual&invoice=1`)
* Supporter signup with credit card payment (`?level=supporter`) 
* Supporter signup with invoice (`?level=supporter&invoice=1`) 

Can we get more information about the signup you didn't hear about @greenreveller @georgiap? Maybe there is something about the particular set of details that they entered which has caused this.

I've [added a test to check that the email](https://github.com/theodi/member-directory/commits/test-members-email-is-copied) which is sent BCCs members@theodi.org.

I don't have access to Mandrill but it sounds like @Floppy has already checked that route in ticket #439.

I'm 99% sure the emails are sent correctly.

**Comment by greenreveller** [comment]
@jordelver these 5 individuals (starting 31 July) we didn't get any email alerts (chargify statement or welcome email): 

David	Tagg-Oram 
Giles 	Dring
Radu 	Puchiu
Josh 	Stephenson
Enas 	Ashraf

For Michele Patron on 4 August I can see a chargify statement but no welcome email

**Comment by greenreveller** [comment]
Also while we've been away Paul Stone and Laura Lewis

NB @bertlewis

**Comment by greenreveller** [comment]
As a temporary measure please could you add andrea.cox@theodi.org and clara.lewis@theodi.org emails as bcc on all auto-generated member welcome emails from mandrill (alongside members@theodi.org). This will need to be both for new individuals and for new organisations. We'll then test it next time a membership comes through.

**Comment by greenreveller** [comment]
And we just got an individual supporter sign-up with members@ bcc'd which was delivered correctly. 

Note to self for the longer term - perhaps this is an issue which affects sign-ups via URLs preloaded with coupon codes rather than through the usual registration URL?

**Comment by greenreveller** [comment]
NB @jordelver 
Just had a new individual supporter come through (colin.horswell@outlook.com). received the chargify statement email but not the member directory welcome email

**Comment by greenreveller** [comment]
This now seems to be working fine - all the last few registration emails are being sent through to members@ and to my personal email address. Closing this ticket now.
