### ISSUE TITLE
Change of membership contact (Pivotal) but no new welcome email triggered

### ISSUE THREAD

**Issue by BertLewis** [theodi/member-directory#468]
I changed the main contact for Pivotal's membership to Michael Natusch yesterday afternoon. Normally this would trigger a new welcome email to the new email address but one hasn't gone out yet.

Can you please check if it's stuck in the queue?

Thanks!

**Comment by greenreveller** [comment]
@jordelver could you take a look at this? could be linked to #459 (e.g. email has been sent to mnatusch@pivotal.io but members@theodi.org is not getting cc'd)

**Comment by jordelver** [comment]
Hi @BertLewis could you show me which email you changed please? A screenshot would be good if you could :)

**Comment by BertLewis** [comment]
No probs Jordan, I changed the email in the membership section of the Capsule entry.
![screen shot 2015-08-27 at 10 53 08](https://cloud.githubusercontent.com/assets/7666636/9517734/e5825aba-4ca9-11e5-9002-d9f43c1f31de.png)

**Comment by jordelver** [comment]
That's great. Thanks :+1: 

So, usually, when you change that Membership Email field, a welcome email is sent to that address?

I'm confused by this at the moment as I can't see where that happens. Has it done this since the beginning or was it a newer feature?

**Comment by jordelver** [comment]
[This seems like the same issue](https://github.com/theodi/member-directory/issues/476) too

**Comment by BertLewis** [comment]
I'm not so sure about that one, @greenreveller can you help out here?

**Comment by BertLewis** [comment]
@greenreveller here is the github ticket for the Pivotal issue

**Comment by jordelver** [comment]
I was reluctant to fix this at the moment due to other problems we've been having with syncing data from Capsule (which this touches). I can manually fix it though in the meantime. I'll have a look later today.

**Comment by jordelver** [comment]
I've updated his email in the member directory and resent the member email. You should of been copied on it. Can you confirm that you were, please? @BertLewis @greenreveller

**Comment by greenreveller** [comment]
@jordelver yes - cc'd. Thanks Jordan!
@BertLewis can you follow up with an email with pivotal to apologise and confirm that they can now login? Cheers
