### ISSUE TITLE
Changes to member email address in Member Directory via Admin Login don't trigger new welcome email

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#473]
I've tested adding a new account email address to the Syngenta account (from derek.scuffell@syngenta.com to sarah.targett@syngenta.com). I would expect to see a new welcome email go out to Sarah in the next couple of hours but haven't seen anything. 

Same issue as #468, #476

**Comment by greenreveller** [comment]
This would be great to fix - but currently workaround is to get tech team to trigger this manually

**Comment by Floppy** [comment]
This functionality is gone now
