### ISSUE TITLE
Change of membership contact for QMUL but no new welcome email triggered

### ISSUE THREAD

**Issue by BertLewis** [theodi/member-directory#476]
Hi, same problem as occurred with Pivotal: have changed the main point of contact for Queen Mary University (OL1531PV) but they have not received their auto-welcome email. Could you check if this one is also stuck?

Thanks.

**Comment by greenreveller** [comment]
@jordelver to manually sort - @greenreveller to raise new ticket to solve the root cause of this problem

**Comment by jordelver** [comment]
I've just changed their email in the member directory and resent the welcome email. You should get copied again.

**Comment by greenreveller** [comment]
confirmed :)

Andrea

Andrea Cox
Membership Manager
@greenreveller <https://twitter.com/greenreveller> @ODIHQmembers
<https://twitter.com/ODIHQmembers>
The Open Data Institute <http://www.theodi.org/>
Tel +44 (0) 7855 456 002

*Summit **2015* <http://summit.theodi.org/> The world's leading event for
showcasing innovation & excellence in open data globally, returns to BFI
Southbank 3 November.
