### ISSUE TITLE
Give all existing organisation members a Member Directory listing

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#479]
As a membership manager I want to display a comprehensive list of all of the organisations who are members on the Member Directory (https://directory.theodi.org/members). I want to do this even if the organisations have not yet composed their company descriptions.
 
I want to apply this rule to existing member organisations as well as new ones - Links to #448 .

I also want the option to remove organisations from the public Member Directory (in the rare instance where a member does not want to be displayed on the Directory).

**Comment by greenreveller** [comment]
Decision that if a member needs removing from the Member Directory then membership team ask tech team to remove said member.

**Comment by jordelver** [comment]
@greenreveller It occurred to me that there may be some test records in the system that we don't want to be shown in the member directory. I've restricted this update to only affect members who have paid through Chargify or have been invoiced.

If you notice anyone who you think should or should not be included, let me know and I'll fix it manually.

I'll need to run this once we're ready:

```ruby
Member.update_all(cached_active: true, "(chargify_payment_id IS NOT NULL OR invoice = 'true') AND product_name IN ('partner', 'sponsor', 'supporter')")
```

**Comment by greenreveller** [comment]
Good idea :+1: 

When you say 'paid through Chargify' will this include those who have been processed through Chargify but not actually paid (e.g. all those who have 100% discount?)

Where can I access the 'organization.active.count' number?

**Comment by jordelver** [comment]
> When you say 'paid through Chargify' will this include those who have been processed through Chargify but not actually paid (e.g. all those who have 100% discount?)

Yes, it will include anyone who has a `chargify_payment_id` in the database which means that they've been processed through Chargify.

> Where can I access the 'organization.active.count' number?

Sorry, that was a note for me. You cannot access it unfortunately, but I can send you the before and after numbers if you'd like?

**Comment by greenreveller** [comment]
Yes please, re before and after numbers. 
Also, why are you working!?

**Comment by greenreveller** [comment]
To be removed from Directory Entry listing: 
Mailchimp SME
Mailchimp SME2
Mailchimp SME3

**Comment by jordelver** [comment]
This is now done @greenreveller. I didn't account for some things but I've fixed it now and cleaned up so we should be good. There were quite a few others "test" accounts showing but I've removed them too.

There were **115** members in the directory before hand and now there are **169**.

**Comment by greenreveller** [comment]
All the companies emboldened in the doc need removing from the member directory: https://docs.google.com/spreadsheets/d/1iJlkA8m3YNeokOScfJ1XY53_qMAE3X-xgSVNKLxWIwE/edit#gid=0

**Comment by greenreveller** [comment]
Manual disentry :(

**Comment by jordelver** [comment]
Done :+1:
