### ISSUE TITLE
Manual creation of NHS England fails

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#481]
Have added membership tag to pre-existing Capsule org entry as per instructions:
- Name
- Email
- Membership tag - Product Name
- Membership tag - Email
https://theodi.capsulecrm.com/party/40483021
Using email xanthe.hannah@nhs.net
However membership creation fails (as per member creation email)

**Comment by greenreveller** [comment]
Attempted to create new company profile for NHS England (using the name NHSEngland) and then tag with membership. Have received error message from Capsule about not enough information: https://theodi.capsulecrm.com/party/88128116?t

Can't see why this is. 

Perhaps with NHS England it's best to delete them entirely from member directory & Capsule and start over? @jordelver what do you think?

**Comment by jordelver** [comment]
Leave it with me. Looking into it now :+1:

**Comment by jordelver** [comment]
I can see that it failed now but not sure why. I'm going to make some changes and re-run it.

**Comment by greenreveller** [comment]
Cheers

**Comment by jordelver** [comment]
I think it's failing because you are using a duplicate email. You can't have the same email twice. I'm looking at how to make this more obvious now.

**Comment by jordelver** [comment]
If you change the email, it will work. But that's obviously not ideal. I can change the old record for you if you'd like?

**Comment by jordelver** [comment]
This should now be fixed. Will wait until tomorrow to confirm.

**Comment by greenreveller** [comment]
Great :+1:

Andrea

Andrea Cox
Membership Manager
@greenreveller <https://twitter.com/greenreveller> @ODIHQmembers
<https://twitter.com/ODIHQmembers>
The Open Data Institute <http://www.theodi.org/>
Tel +44 (0) 7855 456 002

*Summit **2015* <http://summit.theodi.org/> The world's leading event for
showcasing innovation & excellence in open data globally, returns to BFI
Southbank 3 November.

**Comment by jordelver** [comment]
You can probably close this now @greenreveller

**Comment by greenreveller** [comment]
Cool - before I do, can you trigger a welcome email to the main account holder so she can log in?

**Comment by jordelver** [comment]
No problem. I've just done it :+1:
