### ISSUE TITLE
Ensure members (including students) can opt into member marketing/events emails

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#490]
- As a new student member of the ODI I want to be able to opt-in to member communications emails (e.g. newsletter & events emails) on registration. If I opt-out of member communication emails then the only emails I will receive will be related to the administration of my account e.g. renewals emails.  
- As an existing student member of the ODI I initially opted in to member communications. I have now decided that I no longer want to receive newsletters. I have unsubscribed from the membership mailing list by clicking the link at the bottom of a newsletter. I want to make sure that this preference is logged and that I don't receive any more member communications.
- As a membership manager I want to have an easy way for student membership data to be segmented in Mailchimp and Capsule. This is so that we do not send member communication emails to student members who have opted not to receive them (via Mailchimp). 
- As a membership manager I would like mailing lists in Mailchimp to update automatically every day so that I do not have to manually update the list via Capsule every week.

Currently all new members' emails are added to specific Mailchimp member lists on a weekly basis. This is done by syncing a specific Capsule member list (e.g. ODI members (organisations)) with a corresponding Mailchimp member list. 

![image](https://cloud.githubusercontent.com/assets/5023266/9715691/c421c3c4-555a-11e5-8d4f-9e856f2ebbdc.png)

**Comment by greenreveller** [comment]
Relevant Mailchimp lists: 
ODI members (total)
ODI members (organisations)
ODI members (individuals)

**Comment by jordelver** [comment]
I originally thought we should keep using the integration available in Capsule CRM, however, although it works very well, it doesn't do *everything* that we need and I think creating a "hybrid" system where we do some things in Capsule and some in our own code would end up confusing and messy.

My idea now is to create a nightly "job" which subscribes or unsubscribes users from the Mailchimp lists. The basic process being:

```
Select all Membership tagged Capsule members who have been updated in the last 24 hours
  For each member
    Subscribe or unsubscribe them dependent on their newsletter preference
```

This meets your requirement to not have to do any manual intervention.

This does mean that we will need to handle the unsubscribes that happen at Mailchimp though. These happen either through the control panel or unsubscribe links in the emails themselves. This is fairly easily done though, Mailchimp have a "webhook" which can be used to notify us when an unsubscribe happens. When it does, we update the member's newsletter preference to `false` and the information is saved in the member directory database and also sent over to Capsule.

* [X] Write code to handle unsubscribes from Mailchimp
* [ ] Add newsletter checkbox to the signup pages
* [ ] Write job to add or remove people from Mailchimp nightly
* [ ] Test using production data to make sure people stay on lists (perhaps we can also export the mailing lists from live mailing lists for testing?)

**Comment by jordelver** [comment]
One question about the lists @greenreveller. It looks like we have different lists for individuals and organisations. Can we chat about that tomorrow?

**Comment by greenreveller** [comment]
Absolutely. It might be something which we can find a better solution for. Speak then

**Comment by greenreveller** [comment]
Desired fields in Mailchimp: 
First Name
Last Name 
Org Name (if they have)
Newsletter/event emails preferences
Membership tier (supporter, corporate supporter, individual supporter, student)
Sector (as selected on sign-up)
Address
Postcode
Country
Size of organisation
Membership start date
Twitter handle

Potential issues: 
Capsule captures First Name & Last Name for Individual Supporters but Name for Organisation Supporters

**Comment by greenreveller** [comment]
In your checkbox list could you also add 'add newsletter/events emails preferences checkbox to members' account pages'. Cheers

**Comment by greenreveller** [comment]
@jordelver text for the sign-up page: 
To receive the member newsletter and member events emails from the ODI please tick this box

**Comment by jordelver** [comment]
>  In your checkbox list could you also add 'add newsletter/events emails preferences checkbox to members' account pages'. Cheers

@greenreveller could we add this as a separate ticket?

This ticket is in danger of feature creep :)

**Comment by greenreveller** [comment]
Yep - good plan, done

Andrea

Andrea Cox
Membership Manager
@greenreveller <https://twitter.com/greenreveller> @ODIHQmembers
<https://twitter.com/ODIHQmembers>
The Open Data Institute <http://www.theodi.org/>
Tel +44 (0) 7855 456 002

*Summit **2015* <http://summit.theodi.org/> The world's leading event for
showcasing innovation & excellence in open data globally, returns to BFI
Southbank 3 November.

**Comment by jordelver** [comment]
@greenreveller regarding the extra fields you wanted to go into Mailchimp

> Desired fields in Mailchimp: 
> First Name
> Last Name 
> Org Name (if they have)
> Newsletter/event emails preferences
> Membership tier (supporter, corporate supporter, individual supporter, student)
> Sector (as selected on sign-up)
> Address
> Postcode
> Country
> Size of organisation
> Membership start date
> Twitter handle

Could we add this to a new ticket? Some of them rely on other tickets, for example, the first and last names so I'd rather come back to this afterwards if that's ok with you?

**Comment by greenreveller** [comment]
yep done #513

**Comment by jordelver** [comment]
Brilliant, thanks :+1:

**Comment by jordelver** [comment]
@greenreveller do you have an idea where the newsletter checkbox should go on the signup pages?

Under the terms and conditions checkbox maybe?

**Comment by greenreveller** [comment]
I'd like it to go before the password section for all members (for individual members that will be after the 'Are you affiliated with an ODI node' question).

**Comment by jordelver** [comment]
Ok, sounds good :+1:

**Comment by jordelver** [comment]
How does this look?

![2015-09-22 at 09 39](https://cloud.githubusercontent.com/assets/6588/10013975/df8e9eca-610d-11e5-8862-1759c0954b72.png)

**Comment by greenreveller** [comment]
Can we move the box to the end of the 'to receive' text then shift the text to the left so it's in line with the 'Yes, the Node is' text above?

**Comment by greenreveller** [comment]
Test Plan: https://gist.github.com/jordelver/811891aa31dccd27bf4b

**Comment by greenreveller** [comment]
Just signed up again as an SME Supporter (andrea.cox+MailchimpSME2@theodi.org) and ticked the newsletter box. In the capsule entry it's not showing the newsletter box as ticked which it should be.

![image](https://cloud.githubusercontent.com/assets/5023266/10097951/1c81ce06-6375-11e5-9fab-50693832da8f.png)

**Comment by jordelver** [comment]
The newsletter box is unchecked in the database which is why it isn't in Capsule. There maybe a problem with the form. Could you try another one to double check, please?

**Comment by greenreveller** [comment]
Yep - just done one - andrea.cox+MailchimpSME3@theodi.org

**Comment by jordelver** [comment]
Can we chat about this later? I've just signed up using jordan.elver+testing123@gmail.com and the newsletter box is checked so something else is going on here.

**Comment by greenreveller** [comment]
andrea.cox+MailchimpSME@theodi.org
andrea.cox+mailchimpsme2@theodi.org
andrea.cox+mailchimpsme3@theodi.org
All three signed up for newsletter but box not selected in Capsule

**Comment by jordelver** [comment]
Putting a fix together for this now. I think it's because the value of the newsletter preference is not set when you first signup.
