### ISSUE TITLE
Member (SAP UK Ltd) has signed up but not tagging with membership in capsule

### ISSUE THREAD

**Issue by BertLewis** [theodi/member-directory#491]
SAP UK Ltd (AC3231ED) have signed up (we received the auto-email welcoming them) but they haven't been tagged with membership in capsule. Could you please check if they're stuck in the queue? Thanks.

**Comment by jordelver** [comment]
Did they signup via the website @BertLewis?

They seem to have a lot of details missing when I look them up in the database.

**Comment by greenreveller** [comment]
Ah - I think I've spotted what's happening. The guy who has signed up has used his name as the Org name rather than SAP: https://theodi.capsulecrm.com/party/88156537?t

**Comment by greenreveller** [comment]
I think if we amend the org name in the entry we should be ok?

**Comment by greenreveller** [comment]
Have amended their Capsule entry so it's now SAP rather than the guy's name and merged with duplicate: https://theodi.capsulecrm.com/party/84021351. Should be good to go @BertLewis
