### ISSUE TITLE
Amend link to cancellation docuon Individual Supporter registration page

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#492]
Update text underneath orange button on https://directory.theodi.org/members/new?level=individual
so that the text 'right to cancel' links to 'https://docs.google.com/document/d/1CmSGI-hQjcIa0husreVntsxA-5CId3H_BWjRzRmZR6A/edit?usp=sharing'. 

Currently the link goes to a blank page.

**Comment by greenreveller** [comment]
@jordelver would you be able to add this today?

**Comment by jordelver** [comment]
Sure @greenreveller. The Google Doc refers to "Individual supporter". Is that correct?
<img width="691" alt="2015-09-08 at 14 18" src="https://cloud.githubusercontent.com/assets/6588/9735674/51098310-5634-11e5-96f8-0d9c51bce1d1.png">

**Comment by greenreveller** [comment]
Yep, this is just a requirement for sales directly to consumers (as opposed to businesses). 

Cheers

**Comment by jordelver** [comment]
Ok, understood :+1:

**Comment by jordelver** [comment]
Just waiting for this to be merged @greenreveller

**Comment by greenreveller** [comment]
Cheers :+1:
