### ISSUE TITLE
Add password reminder text to membership registration pages

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#494]
Add text "password must be eight characters"  next to the password box on all product registration pages.  oment it isn't stated (a pop up box only pops up when you enter a password which is too short) 

If there are other rules (e.g. must include capitals and numbers then it would be good to flag this up too).

**Comment by jordelver** [comment]
This is done now @greenreveller 

![2015-09-09 at 16 09](https://cloud.githubusercontent.com/assets/6588/9765625/145add2c-570d-11e5-89c2-b50e29829e79.png)

**Comment by greenreveller** [comment]
Great - thanks @jordelver
