### ISSUE TITLE
Cookies affecting users who partially sign-up and then try to sign up again with a discount

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#495]
As an potential Individual Supporter I go to sign-up for membership. I get to the payment page and then abandon my purchase. 
At a later date I attempt to sign-up for membership (but this time using a URL with 100% discount coupon pre-loaded e.g. https://directory.theodi.org/members/new?level=individual&coupon=ODLN). 
I enter my personal data again but when I get to the payment page the discount is not automatically applied. 

I think this is because cookies from the former sign-up attempt are redirecting the user to the payment page from their first sign-up attempt.  Might link with #445 ?

**Comment by jordelver** [comment]
I've fixed this @greenreveller. Just waiting for it to be merged.

**Comment by jordelver** [comment]
Please test at your leisure @greenreveller :)

**Comment by greenreveller** [comment]
Boom! works for me :)
Super speedy @jordelver !
