### ISSUE TITLE
Add new fields to student membership sign-up

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#503]
Additional fields required above what we are already asking for (where possible using drop-down menus). I have starred those fields which are required for registration completion. These fields will also need to be visible in members' account pages. 

Personal Details (standard registration page plus)...
* [x] Date of Birth (display calendar) (required)
* [x] Twitter handle (add for everyone, already exists for organisation profiles, perhaps prefill)

University Details
* [x] University email address
* [x] University address (same fields as the current address we collect)
* [x] Which university are you studying at? (drop-down - https://docs.google.com/spreadsheets/d/1qP2a7Ru_bMb6EoCoB6M6AnFUZ9-_Vki9hVQWjxuxiXI/edit#gid=0) (required)
* [x] What's the name of your course? (text field) (required)
* [x] What qualification are you studying for? (drop-down - https://docs.google.com/spreadsheets/d/1qP2a7Ru_bMb6EoCoB6M6AnFUZ9-_Vki9hVQWjxuxiXI/edit#gid=0) (required)
* [x] What date did you start your course? (display calendar) (required)
* [x] What date do you anticipate completing your course? (display calendar) (required)
* [x] What country is your university in? (drop-down) (required) [NB this will be a hidden field for the pilot]

On the Chargify page: 
* [x] Chargify Coupon field (the field should be visible in Chargify but hidden using page specific Javascript)

@jordelver this is the next piece of work after the mailchimp / capsule mailing list piece. We need quite a lot more data from students. I think it should be easy to import those additional fields into Mailchimp once we have the integration sorted but just wanted to check.

**Comment by greenreveller** [comment]
@greenreveller to ask UUK for open data list of institutions / qualifications

**Comment by greenreveller** [comment]
NB for datasets: 
http://www.hefce.ac.uk/reg/register/ (in XML)
Higher Education Statistics Agency
https://unistats.direct.gov.uk/ -- this video and this video both offer guidance on using Unistats data.
http://www.xcri.co.uk/
https://www.ucas.com/ - not open though!

**Comment by greenreveller** [comment]
Have found an XML file (http://www.hefce.ac.uk/media/HEFCE,2014/Content/Regulation/Register/Data/GatewayRegister.xml) which gets updated weekly which will give us:
*Higher Education Institution name
*Anticipated qualification (eg BA, MA, MEng, BTech, diploma etc)

Questions: 
1. The data is updated weekly - should we aim to update the list every 6 months? 1 year?
2. Data doesn't have an obvious licence - have emailed support team to check

**Comment by greenreveller** [comment]
@jordelver would you be able to incorporate the XML data directly into the registration pages or would you need the data in another format?

**Comment by greenreveller** [comment]
Additional to course name (and to provide a better means of filtering) we could add the field 
*Subject 
and use HESA subject category data (https://www.hesa.ac.uk/dox/dataTables/studentsAndQualifiers/download/Subject1314.xlsx) as a drop-drown (c.15 categories - https://www.hesa.ac.uk/free-statistics). This would provide us a clear way of segmenting the student data. 

ACTION:
@greenreveller to check with Rachel
consider potential problems of using HESA list
licence on data?

**Comment by jordelver** [comment]
> First Name
> Last Name

Isn't this already covered by the existing "Your name" field?
It would be better to change everyone to have separate first and last name fields but will require a significant amount of work so out of scope for this.

> Are you affiliated with a Higher Education Institution? (drop-down) 
Higher Education Institution type (eg college, uni, school) (drop-down)
Subject area (drop-down)
Anticipated qualification (eg BA, MA, MEng, BTech, diploma etc) (drop-down)

Do we have all the data for these dropdowns now? Bit unclear :)

> Course start/projected end dates (display calendar)

So that's start and end date?

> Personal (gmail etc) email address

This is for once the student has left University?

> Student address at university
Country of residence (drop-down)
Personal (home) address

Bit confused by this one. We will already be collecting one address. This should probably be used for "Personal (home) address" and add new fields for "Student address at university"? I don't think we need "Country of residence" in that case?

> Mobile number

Isn't this already covered by the existing "Contact number" field?

**Comment by greenreveller** [comment]
Heya can you take a look at my comments from Tuesday about XML data - that will help me decide if we have the data ready

> Have found an XML file (http://www.hefce.ac.uk/media/HEFCE,2014/Content/Regulation/Register/Data/GatewayRegister.xml) which gets updated weekly which will give us:
*Higher Education Institution name
*Anticipated qualification (eg BA, MA, MEng, BTech, diploma etc)

> @jordelver would you be able to incorporate the XML data directly into the registration pages or would you need the data in another format?

**Comment by greenreveller** [comment]
I have updated the list at the top of the ticket as per your comments: 

> Personal (gmail etc) email address
This is for once the student has left University?

Yes. 

> Student address at university
Country of residence (drop-down)
Personal (home) address
Bit confused by this one. We will already be collecting one address. This should probably be used for "Personal (home) address" and add new fields for "Student address at university"? I don't think we need "Country of residence" in that case?

Yes that makes sense. I want to know where the student lives when they are not at university (including which country that is). I don't need to know the country for their student address as that will be covered by the 'Country of University' field.

Let's have the primary address collected as their home address and then another field for their address while at university.

**Comment by jordelver** [comment]
Re: the data. That XML looks like it gives us what we need although it needs a fair bit of processing. I'm not sure that is in scope for this? Ideally I need just two lists. 

> Yes that makes sense. I want to know where the student lives when they are not at university (including which country that is). I don't need to know the country for their student address as that will be covered by the 'Country of University' field.

Ok, that sounds good but do we need the 'Country of University' field? Seems we should know that (or be able to know that) if we have the University name they are attending? Isn't this UK only Universities anyway?

> Let's have the primary address collected as their home address and then another field for their address while at university.

Ok. Great.

**Comment by jordelver** [comment]
Also a note about design/layout. We're adding quite a few fields here so there will be design and layout decisions to make. I suggest that I do what I think is best for now and I can re-arrange the fields after you've seen it and fed back?

**Comment by greenreveller** [comment]
RE layout - yes that sounds great.

Andrea

Andrea Cox
Membership Manager
@greenreveller <https://twitter.com/greenreveller> @ODIHQmembers
<https://twitter.com/ODIHQmembers>
The Open Data Institute <http://www.theodi.org/>
Tel +44 (0) 7855 456 002

*Summit **2015* <http://summit.theodi.org/> The world's leading event for
showcasing innovation & excellence in open data globally, returns to BFI
Southbank 3 November.

**Comment by greenreveller** [comment]
Decision to hide the 'country of university' field in the student registration form for now. When students from international universities begin to sign up we will need UI to make the field visible.

**Comment by greenreveller** [comment]
The university and qualification lists are in this document: https://docs.google.com/spreadsheets/d/1qP2a7Ru_bMb6EoCoB6M6AnFUZ9-_Vki9hVQWjxuxiXI/edit#gid=0

**Comment by greenreveller** [comment]
I have taken out the 'what subject are you studying' field from the list above - out of scope for the pilot

**Comment by jordelver** [comment]
@greenreveller this is what the signup page looks like for students. Can you let me know any feedback when you get back please :smile: 

![screencapture-localhost-3001-members-new-1444382054944](https://cloud.githubusercontent.com/assets/6588/10390182/e702fe62-6e6e-11e5-88ab-3cd8e5345e51.png)

**Comment by jordelver** [comment]
A couple of other questions:

1) Should the new student fields (including Twitter and DOB) be synced back to the member directory. I assume this makes sense to do but this doesn't seem to be the case for every existing field, so I wanted to check with you.

2) I haven't added the new student fields to the "My Account" page yet. Existing fields for the member's address and the like are not in there already so it seemed weird to add the student fields and leave the others out? Should we include those missing fields? We should probably discuss when you get back.

**Comment by jordelver** [comment]
@greenreveller here is the signup page with changes made

![screencapture-localhost-3001-members-new-1444657838449](https://cloud.githubusercontent.com/assets/6588/10429462/a79113f2-70f0-11e5-8137-8d28dbc71259.png)

**Comment by greenreveller** [comment]
@jordelver to investigate other ways to capture date data for DOB and course start/end date fields

**Comment by jordelver** [comment]
I think I've found one possible solution that seems like it will work for the start and end date of the course. You tell the date picker to start in "year" mode. It looks something like this:

<img width="401" alt="2015-10-15 at 17 07" src="https://cloud.githubusercontent.com/assets/6588/10520290/6071f4be-7361-11e5-97fa-cd1925aedbbf.png">

**Comment by greenreveller** [comment]
Yep - looks like that would work well. Will we be able to get that ready
for user testing tomorrow am? If not, no worries.

Andrea

Andrea Cox
Membership Manager
@greenreveller <https://twitter.com/greenreveller> @ODIHQmembers
<https://twitter.com/ODIHQmembers>
The Open Data Institute <http://www.theodi.org/>
Tel +44 (0) 7855 456 002

*Summit **2015* <http://summit.theodi.org/> The world's leading event for
showcasing innovation & excellence in open data globally, returns to BFI
Southbank 3 November.

**Comment by jordelver** [comment]
This is done now 👍

**Comment by greenreveller** [comment]
Fantastic, thanks @jordelver
