### ISSUE TITLE
Ensure members (including students) can opt into us sharing their details with third parties

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#504]
- As a new member of the ODI I want to be able to opt-in to share my personal details (name and email address and, if relevant, organisation/university name) with third parties. If I opt-out of this then I expect never to receive marketing emails from companies/organisations linked to the ODI (e.g. nodes)
- As an existing member of the ODI I want to be able to change my preferences on third parties by logging into my member account.

- As a membership manager I want to be able to download a list from Capsule of all those members who are happy to share their details with third parties
- As a membership manager I want to be able to segment a member list in Mailchimp so I can see all of the members who are happy to share their details with third parties

**Comment by greenreveller** [comment]
Text for the registration and member account pages:
If you are happy for us to share your personal details with third parties please tick this box

**Comment by greenreveller** [comment]
Included in list of student data requirements in #503

**Comment by jordelver** [comment]
How does this look?

<img width="1136" alt="2015-09-24 at 15 42" src="https://cloud.githubusercontent.com/assets/6588/10076353/132acc56-62d3-11e5-9ef3-ce238b9e974d.png">

**Comment by greenreveller** [comment]
Looks good. Can you change the title text for the section from 'Newsletter' to 'Communication Preferences'?

**Comment by jordelver** [comment]
Sure, good idea :+1:

**Comment by jordelver** [comment]
<img width="1015" alt="2015-09-24 at 15 49" src="https://cloud.githubusercontent.com/assets/6588/10076541/f31711bc-62d3-11e5-81e6-8fe3a0e68421.png">

**Comment by greenreveller** [comment]
Yep, looks great :+1:

**Comment by greenreveller** [comment]
In fact 'Your Communication Preferences' is more in line with the other titles. Ok to change?

**Comment by jordelver** [comment]
Yeah, no problem :)

**Comment by greenreveller** [comment]
Reintroduce checkbox into membership signup form in the communications preferences section (for all membership tiers). 

Change the text to: 

If you are happy for us to share your details with your [local ODI node (theodi.org/nodes)] please tick this box
