### ISSUE TITLE
Add newsletter/events emails preferences checkbox to members' account pages

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#509]

**Comment by greenreveller** [comment]
Currently box says 'send me newsletter'. Change this to 'To receive the member newsletter and member events emails from the ODI please tick this box'

![image](https://cloud.githubusercontent.com/assets/5023266/9961088/855f216c-5e16-11e5-8aa3-c3e456c5a2ca.png)

**Comment by greenreveller** [comment]
Actually changed my mind on the text change we were discussing - leave as is

**Comment by jordelver** [comment]
:+1:
