### ISSUE TITLE
Import new data fields into Mailchimp lists

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#513]
Desired fields in Mailchimp for all members where possible (taken from Capsule CRM)
* [x] First Name
* [x] Last Name 
* [x] Org Name (for organisations)
* [x] Membership tier (supporter, corporate supporter, individual supporter, student)
* [x] Sector (for organisations)
* [x] Country
* [x] Size of organisation (for organisations)
* [x] Membership start date
* [x] Twitter handle

**Comment by jordelver** [comment]
> Newsletter/event emails preferences

They won't be on the mailing list if they have selected to not receive the newsletter so not sure this makes sense?
  
> Address
> Postcode

This is fine but what is the use case for this? How is this useful within Mailchimp?

> Twitter handle

This will only be for students after #503 is done?

**Comment by greenreveller** [comment]
Newsletter/event emails preferences
They won't be on the mailing list if they have selected to not receive the newsletter so not sure this makes sense?

Yes - good point! We can remove from the list

Address
Postcode
This is fine but what is the use case for this? How is this useful within Mailchimp?

As we scale I want to be able to send targeted email campaigns to people in different countries, or different parts of a country (e.g. North England, or places near York). What would be best the data to import to allow us to do that? Possibly City or County is better? 

Secondary issue: we collect billing data in Chargify / for invoicing purposes but it doesn't sit in Capsule for all member types.

Twitter handle
This will only be for students after #503 is done?

Yes

**Comment by jordelver** [comment]
> As we scale I want to be able to send targeted email campaigns to people in different countries, or different parts of a country (e.g. North England, or places near York). What would be best the data to import to allow us to do that? Possibly City or County is better?

Yeah, I should of been clearer. That is what I meant. The whole address is not that useful, county/city is _potentially_ useful but as it's a textbox the data could come in many different ways so I'm not sure it will end up being that useful to filter by in Mailchimp.

> Secondary issue: we collect billing data in Chargify / for invoicing purposes but it doesn't sit in Capsule for all member types.

I'm not sure what you mean by this?

**Comment by greenreveller** [comment]
> Yeah, I should of been clearer. That is what I meant. The whole address is not that useful, county/city is potentially useful but as it's a textbox the data could come in many different ways so I'm not sure it will end up being that useful to filter by in Mailchimp.

Yes, see what you mean. Let's just go for country in the first instance and not export address/postcode. I think if we need to be more granular we will need to alter the address data which is collected on sign-up (which I started to have a think about in #456) so that we have a drop-down list of regions which members choose from. But that is a bigger piece of work. Let's stick with just importing country data for now. 


> Secondary issue: we collect billing data in Chargify / for invoicing purposes but it doesn't sit in Capsule for all member types.
> I'm not sure what you mean by this?

Sorry, I should have been clearer! But this is now irrelevant if we are not transferring address data to Mailchimp

**Comment by jordelver** [comment]
>  Let's stick with just importing country data for now.

Good plan :+1:

**Comment by greenreveller** [comment]
I can see all the required fields in Mailchimp - awaiting #537 for all the relevant data to be updated in Mailchimp e.g. membership join date, level, org sector

**Comment by greenreveller** [comment]
I've had a look through the data and there are some gaps in it. I can't see any obvious patterns for who remained on the list and who is off it (they seem to be at random rather than by a particular category). Here are some examples: 

Individual Supporters
There are only 47 individual supporters on this master its therefore c.87 individual supporters compared with the original (ODI members total) list. 
Filip Manevski FX9388BJ
Raju Rayasam YC4094HB
Abigail Rumsey IW1257LR

Missing Partners e.g. 
Richard Whale (Experian) AQ1298ST

Supporters - 96 entries missing e.g.
Joe Short (Demand Logic) HX6714LA

I had originally thought that it was the manual additions to the old mailing lists which had dropped off this master list but I can confirm that this is not the case. 

@jordelver - are you able to see for these specific cases why they didn't come across from Capsule?

**Comment by jordelver** [comment]
The specific examples you give above all don't have their newsletter box ticked so that's why _they_ are not on the list.

**Comment by greenreveller** [comment]
Good point. But I thought that the newsletter box had been hidden from the registration form for a long time before we made the changes in #490? If that's the case why would there be a mixture of ticked and unticked newsletter boxes in Capsule do you think?

**Comment by jordelver** [comment]
Hmm, that _is_ a good question. Although the preference has been in the "My Account" page for a while hasn't it?

**Comment by greenreveller** [comment]
Yes that's true. I think the default on the 'My Account' page is to have
the newsletter unticked so perhaps all those currently on the list have
gone into their accounts and updated their entries.

Might be a manual job then to click the 'newsletter' box in Capsule for all
those members who we know haven't unsubscribed from the Mailchimp list.

Andrea

Andrea Cox
Membership Manager
@greenreveller <https://twitter.com/greenreveller> @ODIHQmembers
<https://twitter.com/ODIHQmembers>
The Open Data Institute <http://www.theodi.org/>
Tel +44 (0) 7855 456 002

*Summit **2015* <http://summit.theodi.org/> The world's leading event for
showcasing innovation & excellence in open data globally, returns to BFI
Southbank 3 November.
