### ISSUE TITLE
New Corporate Supporter listed by person name rather than org name

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#518]
They bought a Summit & membership package (via Eventbrite). 

Currently the Supporter organisation name is the attendee's name (Harry Tull) in Capsule. We need to change the org name field to Turner & Townsend in capsule and the member directory. 

Organisation: Turner & Townsend 
Email: harry.tull@turntown.co.uk

Similar to #491 

@jordelver how is it best to do this - from your end or mine?

**Comment by jordelver** [comment]
If you change the name in the membership tag it should get saved over to the membership directory.

**Comment by greenreveller** [comment]
Do you mean the Org Name in Capsule? 

I can't see how to edit the membership tag info :/

**Comment by jordelver** [comment]
Ready for testing now @greenreveller 

You should be ok to change the name in Capsule now
<img width="670" alt="2015-09-24 at 14 04" src="https://cloud.githubusercontent.com/assets/6588/10074042/4861f164-62c5-11e5-89b9-fc49369790fa.png">

**Comment by jordelver** [comment]
We have disabled the Eventbrite integration for now. That should stop these errors happening.

**Comment by greenreveller** [comment]
:+1: going to close :)
