### ISSUE TITLE
Update member email address

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#529]
For member 'Ontotext AD' change email address in member directory to: finance@ontotext.com

**Comment by jordelver** [comment]
This is changed now @greenreveller

**Comment by greenreveller** [comment]
Thanks @jordelver

**Comment by greenreveller** [comment]
Hiya Jordan, normally we would see a welcome email come through after a change of member email address - I haven't seen one so far. Can you see anything on your end?

**Comment by jordelver** [comment]
Sorry, I have to manually trigger it and failed to do so. I've done it now :+1:
