### ISSUE TITLE
Member has cancelled but their Directory Entry is still showing

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#532]
Member 'Dialogue by Design' are no longer tagged with 'Membership' in Capsule. However, they are still showing up in the Member Directory (https://directory.theodi.org/members/ON9682OI). 

@jordelver this hasn't happened before as far as I remember - can you see any reason why this might happen?

**Comment by jordelver** [comment]
I'm not sure why this happened but I've removed them manually.

**Comment by greenreveller** [comment]
:+1:
