### ISSUE TITLE
Member's  Capsule entry is missing data (but I can't see where)

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#535]
Error email message sent from Capsule at 11.25, 17.05 and 18.05 yesterday saying that the individual supporter member profile (Gerald Milward-Oliver) has not been updated correctly. For context I added this individual Supporter manually yesterday c.10am.

![image](https://cloud.githubusercontent.com/assets/5023266/10480303/65140c74-7261-11e5-8e96-eb45be1f26de.png)

It looks as if a Member ID has not been allocated to the Gerald but I'm not sure why...

**Comment by jordelver** [comment]
There seems to be two copies of this person now.

https://theodi.capsulecrm.com/party/87351337
https://theodi.capsulecrm.com/party/90625807

The first one does have a membership ID now. 

I did fix a problem with syncing the other day but that was student related.

**Comment by jordelver** [comment]
This is one I was talking about this morning @greenreveller
