### ISSUE TITLE
Import supporter level field from Capsule into Mailchimp member list

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#542]
As a membership manager I need to be able to differentiate the two types of individual memberships (individual & student) and the two types of supporter membership (supporter and corporate). 

Can these easily be added into the sync process as per #513 ?

* [x] Make student "Level" be "individual"
* [x] Send "Supporter level" as well as "Level" to Mailchimp

**Comment by jordelver** [comment]
This refers to the **Level** and **Supporter Level** Membership tags.

![2015-10-21 at 14 14](https://cloud.githubusercontent.com/assets/6588/10637512/075b9294-77fe-11e5-82b3-d7bec74be74f.png)

For student members, the **Level** should be "supporter" and **Supporter Level** should be "student".

**Comment by jordelver** [comment]
I think my notes above are incorrect :( It makes more sense that students would have a **Level** of "individual" and a **Supporter Level** of "Student".

This is how it will look in CapsuleCRM now:

![2015-11-04 at 11 26](https://cloud.githubusercontent.com/assets/6588/10936857/1ba0c2d0-82e7-11e5-9008-bb5e8e1b384d.png)

**Comment by greenreveller** [comment]
Agree - that makes more sense

Andrea

Andrea Cox
Membership Manager
@greenreveller <https://twitter.com/greenreveller> @ODIHQmembers
<https://twitter.com/ODIHQmembers>
The Open Data Institute <http://www.theodi.org/>
Tel +44 (0) 203 771 3094


Latest from the ODI:

News ODI welcomes new role with Cabinet Office: forging stronger connection
between data innovators and Central Government
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsRbwvTVS9SW83M1wmHN3D5Xyz11w36f45flx803?t=http%3A%2F%2Ftheodi.org%2Fblog%2Fodi-welcomes-new-role-with-cabinet-office%3Futm_content%3Dbuffercc555%26utm_medium%3Dsocial%26utm_source%3Dtwitter.com%26utm_campaign%3Dbuffer&si=5868787787628544&pi=af57dd46-380f-4ad9-9b4b-3a5967b69427>

News Over £40M value unlocked in ODI's first three years
<http://t.sidekickopen01.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJN7t5XZsRbwvTVS9SW83M1wmHN3D5Xyz11w36f45flx803?t=http%3A%2F%2Ftheodi.org%2Fnews%2Fodi-40m-value-unlocked-worldwide&si=5868787787628544&pi=af57dd46-380f-4ad9-9b4b-3a5967b69427>
