### ISSUE TITLE
Member profile updated on Directory, profile becomes inactive

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#543]
I updated SAP's Directory Entry profile with some new text via https://directory.theodi.org/members/AC3231ED and clicked save.

When I go to check the Entry I find they are no longer showing on the Member Directory at all.

@jordelver any ideas?

**Comment by greenreveller** [comment]
I realised that I needed to click 'active' in Capsule in order to make this live. Now the directory entry is showing. My question is how will the membership team know if a member makes an update to their directory entry which needs our review?

**Comment by jordelver** [comment]
You shouldn't need to "activate" a member's profile after it is updated so this may be a bug.

**Comment by greenreveller** [comment]
When we had a new member sign up last week this didn't happen. I think it's a bug which happens occasionally - I'm going to move this to the backlog and we'll reassess as and when it comes up again.

**Comment by jordelver** [comment]
:+1:
