### ISSUE TITLE
Student registration does not affect coupon count in Chargify

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#545]
Beth Cooper (MQ7602CP) registered as a student using https://directory.theodi.org/members/new?level=student&origin=university&coupon=STARFLEET but the use of the coupon is not registered in Chargify. 

![image](https://cloud.githubusercontent.com/assets/5023266/10539719/8db98bf6-73f9-11e5-8eaf-f1f99b1055cf.png)

**Comment by jordelver** [comment]
This is a Chargify configuration issue. The coupon was part of a different "product family". It was decided that the coupon would be moved to the correct family for now. We might change to a different product family in the future.

**Comment by greenreveller** [comment]
All testers signed up using: https://directory.theodi.org/members/new?level=student&origin=university&coupon=STARFLEETACADEMY

The coupon is assigned to the individual supporter - student product in Chargify 

But the coupon still is not showing up as being used in Chargify :(

![image](https://cloud.githubusercontent.com/assets/5023266/10732465/1c0fdd9c-7bf2-11e5-91a9-00389eb697cc.png)

**Comment by jordelver** [comment]
I've applied a fix that I'm hoping should fix this. Can you try it again, please?

**Comment by greenreveller** [comment]
just tested - still no joy :(
using https://directory.theodi.org/members/new?level=student&origin=university&coupon=STARFLEETACADEMY

![uploads/8a915c9d-fb8a-49a1-872d-ff74b6266f85/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F8a915c9d-fb8a-49a1-872d-ff74b6266f85%2Fblob)
