### ISSUE TITLE
Remove requirement to specify day for course start and course end date fields

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#548]
As a membership manager I don't need to know the precise day that a student started their course. Can we simplify the calendar in these two cases so that it only asks you for month and year?

**Comment by jordelver** [comment]
After having a think, we might need to have a chat about this one. It might be an idea to change to two dropdowns, one for month and one for year?

**Comment by greenreveller** [comment]
Yes, that would work for me. Esp as the start year will only need to go back to 2010 at the earliest.
