### ISSUE TITLE
Coupon SUMMIT2015 doesn't seem to be applying the discount 

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#552]
We recently created a SUMMIT2015 coupon (for £100 discount of organisation membership) in Chargify. A member has come back unable to see the £100 discount applied to their purchase using URL https://directory.theodi.org/members/new?level=supporter&coupon=Summit2015. 

When they get through to Chargify page the price is shown as £720 + VAT rather than £620 + VAT. 

NB I set this coupon up end of last week and when I did a dry run it was working fine. Just tested it again and I'm getting the same problem.

**Comment by jordelver** [comment]
Is that the actual used? I _think_ coupons are case sensitive and should be uppercase in this case. Can you try with it uppercase if you haven't already?

**Comment by greenreveller** [comment]
aha! I'll try now...

Andrea

Andrea Cox
Membership Manager
@greenreveller <https://twitter.com/greenreveller> @ODIHQmembers
<https://twitter.com/ODIHQmembers>
The Open Data Institute <http://www.theodi.org/>
Tel +44 (0) 7855 456 002

*Summit **2015* <http://summit.theodi.org/> The world's leading event for
showcasing innovation & excellence in open data globally, returns to BFI
Southbank 3 November.

**Comment by greenreveller** [comment]
good spot - that works fine. I'll get back to them. Cheers

**Comment by greenreveller** [comment]
I just tried this again using: https://directory.theodi.org/members/new?level=supporter&coupon=SUMMIT2015 on Safari and the discount wasn't applied :/

@jordelver can you take a look when you have a moment? This is pressing as we have sent the coupon URL to a member who will try to sign up and use it....

**Comment by jordelver** [comment]
It's not being accepted because it is not a percentage based discount.  [We decided to restrict coupon to percentage based only here for Xero / accountancy reasons](https://github.com/theodi/member-directory/commit/6b1f5248).

**Comment by greenreveller** [comment]
Good find - had totally forgotten about that. (weird that sometimes the discount was being applied at flat rate and sometimes not thought). For now I have converted the flat rate discount into an approximate %. @jordelver can you let me know when Sam has rebooted the system?

**Comment by jordelver** [comment]
Will do :+1:
