### ISSUE TITLE
After adding org supporter manually their Directory Entry is not live

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#558]
Member BO9966QO were added yesterday. Their name has not gone up on Member Directory (I think because they have not yet logged in). There is no option to for me to click 'active' in their Capsule entry either. Ideally we want all members to have a Directory profile as soon as they sign up as per #479

**Comment by greenreveller** [comment]
![image](https://cloud.githubusercontent.com/assets/5023266/10689089/96e893bc-7970-11e5-9887-9e746ddfb61d.png)

**Comment by jordelver** [comment]
I think this is happening partly because they are only made active after paying through Chargify which does not happen when you add people manually. I will review how it works and see how we can workaround.

**Comment by greenreveller** [comment]
Update: the member is now live - I think probably owing to them logging on. Ticket still needs addressing

**Comment by jordelver** [comment]
Check when the directory entry tag gets set on the member as that is what controls whether they end up in the directory.
