### ISSUE TITLE
Import Stripe customer data into Chargify

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#571]
As membership manager I need all members who pay by credit card for membership to be in Chargify. Currently we have c.10 members who pay via Stripe but are not in Chargify. Ideally I would like to transfer their payment data into Chargify via the API (to avoid having to chase these members to upload their details to Chargify). However, I am not yet clear if this will be possible.

**Comment by greenreveller** [comment]
#273 might be relevant

**Comment by greenreveller** [comment]
@greenreveller to create a list of all who are affected and share
Plan to add these manually by turning off payment requirement for particular products temporarily.

@jordelver to see if we need to add some extra code to these customers' member records in Member Directory to show that they are now being charged in Chargify. Do we need this for automated cancellation purposes?

**Comment by jordelver** [comment]
The fields in the member directory are:

```
chargify_customer_id
chargify_subscription_id
chargify_payment_id
chargify_data_verified
```

**Comment by greenreveller** [comment]
Manual solution found to this issue. Add members on student product in Chargify first (so that you do not require payment) and then change their product accordingly
