### ISSUE TITLE
Can we make text bigger on Chargify payment page?

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#585]
![image](https://cloud.githubusercontent.com/assets/5023266/10732157/aa279248-7bf0-11e5-98f6-607e68258e9b.png)

Make the 'Free membership of the ODI for the ....' text bigger so it's easier for users to see (but not as big  as the 'Become a member of the ODI' text).

**Comment by jordelver** [comment]
This is done now :+1: 

![2015-10-28 at 15 38](https://cloud.githubusercontent.com/assets/6588/10793813/60a6c30a-7d8a-11e5-8c08-20eb15216743.png)

**Comment by greenreveller** [comment]
Great stuff :)

Andrea

Andrea Cox
Membership Manager
@greenreveller <https://twitter.com/greenreveller> @ODIHQmembers
<https://twitter.com/ODIHQmembers>
The Open Data Institute <http://www.theodi.org/>
Tel +44 (0) 7855 456 002

*Summit **2015* <http://summit.theodi.org/> The world's leading event for
showcasing innovation & excellence in open data globally, returns to BFI
Southbank 3 November.

**Comment by greenreveller** [comment]
Just tested but still showing up small for me:

**Comment by jordelver** [comment]
This was a configuration problem @greenreveller. The student product has two public signup pages, paid and free.

This is what they look like now I've fixed the configuration.

**Paid** https://theodi.chargify.com/subscribe/wyqh5zhrxq5z/individual-supporter-student

![2015-11-19 at 11 10](https://cloud.githubusercontent.com/assets/6588/11269322/35c2ca5a-8eae-11e5-9804-313afd25c626.png)

**Free** https://theodi.chargify.com/subscribe/vpvdyjxfktq9/individual-supporter-student

![2015-11-19 at 11 09](https://cloud.githubusercontent.com/assets/6588/11269317/2ce29cf8-8eae-11e5-938a-81317704cdc4.png)
