### ISSUE TITLE
New member - no welcome email to members@ and not showing in Capsule

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#588]
Member KF8474WD (Agro-Know) registered as an organisation sometime last week. We (members@theodi.org) were not alerted via a welcome email. 

We noticed that they are appearing on the Member Directory but not in Capsule. 
They are showing correctly in Xero and have been invoiced.

@jordelver can you see why they didn't make it through to Capsule and if their welcome email was sent?

**Comment by jordelver** [comment]
I'm not sure what's going on with it unfortunately :( I've fixed it manually in Capsule. I checked to see if a welcome email was sent and I couldn't find anything so I resent it.

**Comment by greenreveller** [comment]
Finance have just flagged that they can't see the payment for this account in Xero (we think they raised an invoice). They would have used the Coupon SUMMIT2015 when they were booking. The Supporter says that they have already paid. 

Could you have a look to see if you can see any info in the directory about their payment? cheers
