### ISSUE TITLE
Individual Supporters showing up with wrong amount in Xero

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#590]
Individual Supporters are still coming through as £108 plus VAT which is incorrect. 

Should be coming through as £90 + VAT. 

![image](https://cloud.githubusercontent.com/assets/5023266/10761276/8494c898-7cb8-11e5-982e-5e4677f24081.png)

NB Although we don't send invoices to Individuals we still need the amounts to be correct in Xero

**Comment by jordelver** [comment]
I _thought_ this was fixed a while ago. Try and find that "fix".

**Comment by jordelver** [comment]
This is an issue now
