### ISSUE TITLE
Add new student membership product to Member Directory

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#598]
I've created a new £36 student product so that students who sign up through the ODI website can be charged for membership (rather than get it for free). 

I have created the product within the individual supporter family in Chargify with API handle individual-supporter-student-public.

The registration pages should mirror exactly the standard student registration pages other than that payment will be requested on the Chargify page. 

A few things: 
* [x] Please could you check that the product is set up correctly in Chargify for your purposes?
* [x] Ensure new product is recognised in the Member Directory
* [x] Ensure new product is recognised in Capsule
* [x] Copy the standard student registration pages for this new product
* [x] The signup page URL should read: https://directory.theodi.org/members/new?level=student-public&origin=university 
* [x] Home address data on the Member Directory page should pre-fill the billing address data fields on the Chargify page

**Comment by jordelver** [comment]
This is now done and uses the same product as existing students.

The only difference is that they use different **public signup pages** within Chargify. This allows us to skip the payment and billing details for certain students.

The URL will look like this:
https://directory.theodi.org/members/new?level=student&free=true&origin=university&coupon=COUPON

**Comment by greenreveller** [comment]
@greenreveller to provide T&Cs for paid for product
