### ISSUE TITLE
Unticked 'active' in Capsule member profile - still showing in Member directory

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#602]

**Comment by greenreveller** [comment]
IRICSS have cancelled their membership - I want to remove their directory entry profile. I unticked 'active' in their Capsule profile yesterday. But this has not synced with Directory Entry today: 

IRICSS https://directory.theodi.org/members/II4318ME

![uploads/beb15435-8159-44b0-adef-565ea995d406/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fbeb15435-8159-44b0-adef-565ea995d406%2Fblob)

**Comment by greenreveller** [comment]
QX8554BI 
GF9466MY
II4318ME

All to be removed manually from the Directory Entry please.

**Comment by jordelver** [comment]
These three have been made inactive. Did you say there were more to come?

**Comment by greenreveller** [comment]
CO3865PL
WR2711VX
QX8554BI
GF9466MY
BL5501BD
NQ9917YW
IV5965BU

**Comment by jordelver** [comment]
These are done too now.

**Comment by greenreveller** [comment]
Make sure that you untick active in Capsule. Then wait to see if company directory entry removed. Once removed then you can remove membership tag.
