### ISSUE TITLE
Recurring Capsule error messages for two members

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#604]
http://theodi.capsulecrm.com/party/91248747 - individual Supporter

http://theodi.capsulecrm.com/party/76319474 - org Supporter (possibly a result of me merging two entries in Capsule?)

In both cases I _think_ that the fields have been filled out correctly so I'm not sure why we are getting error messages

**Comment by greenreveller** [comment]
![uploads/a1d5030b-d464-4bff-957d-1aa4e8a80d2a/blob](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fa1d5030b-d464-4bff-957d-1aa4e8a80d2a%2Fblob)

**Comment by greenreveller** [comment]
The next time this comes up make sure we are only adding the data specified in these error messages (no additional data) and monitor.

**Comment by jordelver** [comment]
Add note to email that the cause of failed members could be because of duplicate emails in the member directory itself.
