### ISSUE TITLE
Added student manually to Capsule, wrong welcome email received

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#608]
We added a new person to Capsule yesterday and tagged them with student. We added the following level and supporter level fields as per #542: 

![image](https://cloud.githubusercontent.com/assets/5023266/11113561/d83c5dbc-8915-11e5-8808-7d31d7e1fed2.png)

Instead of receiving the student welcome email they received the individual Supporter email. 

![image](https://cloud.githubusercontent.com/assets/5023266/11113496/59391910-8915-11e5-9612-dab9d7667531.png)

When students have registered themselves they show up as Individual, Student in Capsule and receive the correct welcome email so not sure what's going on here :/

Can you look into and liaise with @juliehitgub? She will be adding students manually today so we need a fix ASAP. Cheers,

**Comment by jordelver** [comment]
This is happening because the students are being created in the member directory as "individuals", not "students" because of a syncing bug.

**Comment by jordelver** [comment]
If you give me a list of student membership numbers who you have manually created @juliehitgub, I will fix their records manually.

**Comment by Juliehitgub** [comment]
I'll try and get that info together now Jordan.

Shall I input students as instructed (level: individual, supporter level:
student)?



On 12 November 2015 at 10:26, Jordan Elver <notifications@github.com> wrote:

> If you give me a list of student membership numbers who you have manually
> created @juliehitgub <https://github.com/juliehitgub>, I will fix their
> records manually.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theodi/member-directory/issues/608#issuecomment-156062310>
> .
>



-- 
Julie McMahon, Membership Administrator
+44 (0) 20 3598 9395

The Open Data Institute, 65 Clifton Street, London EC2A 4JE
<http://www.theodi.org/>
