### ISSUE TITLE
Two Capsule entries accidentally created for Student - can we merge?

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#612]
We have the following entries for the same person: 

https://theodi.capsulecrm.com/party/92447651
https://theodi.capsulecrm.com/party/92519608

The first entry (ending 651) is missing most data except for member ID. 

The second entry is complete except for Member ID. 

We'd like to merge the two Capsule entries so that only the one entry (ending 651) remains. From your pov are we ok to merge? 

The same issue has cropped up for another Student: 
https://theodi.capsulecrm.com/party/92447326
https://theodi.capsulecrm.com/party/92678755

cc @juliehitgub

**Comment by jordelver** [comment]
It should be ok from my point of view as it's the email and membership id which are used to sync *crosses fingers*

**Comment by greenreveller** [comment]
ok cool - here goes...
