### ISSUE TITLE
Create script to automatically add 800 students to member directory

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#614]
This is to avoid having to manually add students via Capsule

**Comment by greenreveller** [comment]
@Floppy can you let me know before this goes live? Think we should plan some testing on dummy data. 

Cheesr,

**Comment by Floppy** [comment]
The initial version without Chargify support (because awkward) will go up this morning, and I've got a half hour scheduled in with Rachel to do some testing at 11. Definitely agreed we should test :)

See #620
