### ISSUE TITLE
Ensure that students who have been added manually get a personalised welcome email

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#615]
As discussed

**Comment by jordelver** [comment]
We need to save their contact name when creating them in the member directory

**Comment by jordelver** [comment]
Can you test this please @greenreveller? :D

**Comment by greenreveller** [comment]
Hiya, just tested and I'm still seeing a comma (andrea.cox+personalised@theodi.org)

![image](https://cloud.githubusercontent.com/assets/5023266/11399689/e35d0c62-9380-11e5-8dc8-3fe5b0c4e368.png)

**Comment by jordelver** [comment]
Computars are the worst!

Can you try it again please, I believe I have fixed the issue :)

**Comment by greenreveller** [comment]
Yep all working now :)

![image](https://cloud.githubusercontent.com/assets/5023266/11421178/25fcf55a-942b-11e5-845c-baeb3a1a1c47.png)

**Comment by jordelver** [comment]
:+1:
