### ISSUE TITLE
Student being asked for card details on registration

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#619]
Student receiving the following Chargify error messages when signing up using  https://directory.theodi.org/members/new?level=student&free=true&origin=university&coupon=HALLAM2015

![image](https://cloud.githubusercontent.com/assets/5023266/11535044/f164465c-9909-11e5-8455-3eeb010a27fb.png)

NB lots of other students successfully signed up using the same link. I asked this student to sign up using Chrome but he is still having the same problem.

**Comment by greenreveller** [comment]
Hi @jordelver, if you have time this morn could you have a look?

**Comment by jordelver** [comment]
I’m wondering whether something went wrong when he tried to pay with Chargify. Then, when trying to pay again by signing in (he's signed in 3 times) he's then getting sent to the wrong payment page.

**Comment by jordelver** [comment]
Possible solution might be to keep the payment parameters in the session for when people try again, but this won't fix all cases. It would be nice to know why the initial payment failed.

**Comment by greenreveller** [comment]
I added this student member (Jon Smart) manually via Capsule yesterday (after making sure his email was deleted from the directory after 3 failed signups - see above). Now when he tries to login he is getting the following error message: 

Hi,
 
Many thanks for registering my membership. When I click the link to activate my membership, and try to set my password as requested, I’m getting an error message advising that my Reset password token has expired.
 
![image](https://cloud.githubusercontent.com/assets/5023266/11589488/e3482c00-9a80-11e5-878f-b7cfad2a5440.png)

@Floppy could you take a quick look to see what's happened? This would make my day better :)

**Comment by Floppy** [comment]
should be done now
