### ISSUE TITLE
Send welcome email to new contact for DW5891ER

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#624]
Hiya @Floppy 
Please could you trigger a welcome email for averil.clother@bulmerfoundation.org.uk so she can set a password and sign in.

Cheers,

**Comment by Floppy** [comment]
This might have already been done - @juliehitgub is this still required?

**Comment by Juliehitgub** [comment]
Do you have record of it being completed, I'm following it up as it seems
to be outstanding but it was originally raised by Andrea, would a note have
been sent to her?

Bulmer were registered on 27/11/15 and have an Capsule ID, but I don't have
any trace of a Welcome Email. They don't have an entry on our Directory
either.

Julie McMahon, Membership Administrator
+44 (0) 20 3598 9395

The Open Data Institute, 65 Clifton Street, London EC2A 4JE
<http://www.theodi.org/>

**Comment by Floppy** [comment]
Aha - the email in the DB doesn't match Averil's. Will check with Julie.

**Comment by Floppy** [comment]
Reading this ticket completely again (including the title), I think we need to change the email and resend the invite. I'll do that and we'll be done with it.

**Comment by Floppy** [comment]
Updated everything to send to Averil, and sent. Should now be fine.

**Comment by Juliehitgub** [comment]
Thanks.

Julie McMahon, Membership Administrator
+44 (0) 20 3598 9395

The Open Data Institute, 65 Clifton Street, London EC2A 4JE
<http://www.theodi.org/>
