### ISSUE TITLE
Chargify integration needs attention ASAP

### ISSUE THREAD

**Issue by greenreveller** [theodi/member-directory#627]
We've had an error message come up on Chargify re API integration. @Floppy @pezholio please could you have a look? 

https://app.chargify.com/tls_check

**Comment by Floppy** [comment]
This depends on the underlying openssl version in use, and from that check page it looks like only test machines (i.e. local development) has the problem. The production servers are running openssl 1.0.1f-1ubuntu2.15, which should be fine and support TLS 1.2. On my Mac (running El Capitan!), openssl is 0.9.8zg, which might have problems. So, I think this is only an issue for development, not production. That means we can deal with our macs when we need to do more dev.

@pikesley @pezholio FYI.

**Comment by Floppy** [comment]
BTW @greenreveller thanks very much for the warning :)
