### ISSUE TITLE
Member Directory update changes to status, Telefonica and Socrata

### ISSUE THREAD

**Issue by Juliehitgub** [theodi/member-directory#631]
Please could 
1. Telefonica have their green badge removed in the Member Directory, they did not renew their partnership, but are a corporate member
2. Socrata are no longer a sponsor, could their entry in Member Directory be updated

**Comment by Floppy** [comment]
I think this can be done through capsule. Will have a go. If not, I can use the admin interface to do it.

**Comment by Floppy** [comment]
Have made the changes, will wait for the queue to do the sync and make sure it works as expected.

**Comment by Floppy** [comment]
Socrata is OK now... Telefonica not quite right. Checking.

**Comment by Floppy** [comment]
And Telelfonica too. Needed the membership tag re-adding as the fields had changed since it was added long long ago, but after that the update worked.
