### ISSUE TITLE
Deutsche Bank, membership creation failure

### ISSUE THREAD

**Issue by Juliehitgub** [theodi/member-directory#633]
Created Capsule entry for new corporate member Deutsche Bank on 18/12/15. So far have had several Membership Creation Failure emails and their membership has not been acknowledge, i.e. have not received our Welcome email.

**Comment by Floppy** [comment]
@ayymanduh keep an eye on this for updates :)

**Comment by Floppy** [comment]
@juliehitgub @ayymanduh Membership is now created and email has been sent to JP. Reason was that the supporter type (which is manually entered) was wrong in capsule. That's a bit too error-prone, unfortunately.

**Comment by Juliehitgub** [comment]
Thanks. I entered this manually so it was my mistake, sorry. If you let me know what the error was I'll be aware next time.
