### ISSUE TITLE
Student member has record in Capsule but no ID

### ISSUE THREAD

**Issue by Juliehitgub** [theodi/member-directory#637]
Steven Foster, Dundee University, was sent our Welcome email on 15/12/15. There is no ID in the email, and he does not have a record in Capsule.

**Comment by Floppy** [comment]
Doesn't have capsule or does? Title and text are contradictory :)

**Comment by Juliehitgub** [comment]
Sorry. Has Capsule record but no ID. There is also no record of him in Chargify.

**Comment by Juliehitgub** [comment]
Has Capsule record with no ID ref, has no record in chargify. Sorry.

Julie McMahon, Membership Administrator
+44 (0) 20 3598 9395

The Open Data Institute, 65 Clifton Street, London EC2A 4JE
<http://www.theodi.org/>

**Comment by Floppy** [comment]
That's resolved. I updated the capsule entry manually and it triggered a membership number generation, email etc. I suspect this got lost in the queue stall.

**Comment by Juliehitgub** [comment]
Got email for this one, thanks
